# Generated by scripts/gen_int_boundary.py -- do not edit by hand.
#
# Crosses every boundary of the tagged small-int representation
# (+-2**62) against every operator that codegen inlines.

vals: list[int] = [
    0,
    1,
    -1,
    2,
    -2,
    3,
    -3,
    7,
    -7,
    97,
    -97,
    2147483648,
    -2147483648,
    2147483647,
    -2147483649,
    4294967296,
    2305843009213693952,
    -2305843009213693952,
    4611686018427387903,
    4611686018427387902,
    4611686018427387904,
    -4611686018427387904,
    -4611686018427387903,
    -4611686018427387905,
    9223372036854775807,
    -9223372036854775808,
    9223372036854775808,
    18446744073709551616,
    1000000000000000000000000000000,
    -1000000000000000000000000000000,
]
n = len(vals)
for i in range(n):
    a = vals[i]
    print(a, -a, ~a, a == 0, a < 0)
    for j in range(n):
        b = vals[j]
        print(a + b, a - b, a * b)
        print(a < b, a <= b, a > b, a >= b, a == b, a != b)
        print(a & b, a | b, a ^ b)
        if b != 0:
            print(a // b, a % b)

# Division by zero keeps its exact type, message and catchability: the inline
# fast path routes a zero divisor to the runtime rather than trapping itself.
for i in range(n):
    a = vals[i]
    try:
        print(a // 0)
    except ZeroDivisionError as e:
        print("floordiv", e)
    try:
        print(a % 0)
    except ArithmeticError as e:
        print("mod", e)
