//! Lowers the typed IR to LLVM IR in its textual format.
//!
//! The textual IR is the serialization boundary handed to the C++ shim,
//! which parses, verifies, optimizes and emits native object code.
//!
//! Semantics preserved from Python:
//! - `//` and `%` use floored division (result sign follows the divisor)
//! - division by zero traps with a ZeroDivisionError message instead of UB
//! - `int(float)` is a saturating conversion (no UB on NaN/overflow)
//! - `i64::MIN // -1` wraps instead of being UB (select on the divisor)
//! - `**` on ints uses runtime repeated squaring (negative exponent traps);
//!   `0.0 ** negative` traps like Python instead of returning inf
//!
//! Strings are length-prefixed `{ i64, [n x i8] }` blobs; lists are
//! `{ len, cap, data }` headers with 8-byte value slots. Both live behind
//! `ptr` and are managed by the C runtime (allocated, never freed).
//!
//! All user symbols are prefixed `pyrs_` so they can never collide with
//! libc symbols (a user function named `printf` is fine).

use std::collections::HashMap;
use std::fmt::Write;

use ir::{BinOp, Expr, ExprKind, FileFn, Function, Module, Stmt, StrFn, Ty, UnOp};

pub fn emit_llvm_ir(module: &Module) -> String {
    let mut e = Emitter::default();
    e.emit_module(module);
    e.finish()
}

fn lty(ty: Ty) -> &'static str {
    match ty {
        Ty::Int => "i64",
        Ty::Float => "double",
        Ty::Bool => "i1",
        Ty::Str => "ptr",
        Ty::List(_) => "ptr",
        Ty::File => "ptr",
        Ty::None => "void",
    }
}

fn mangle(name: &str) -> String {
    format!("pyrs_{name}")
}

/// LLVM hexadecimal float syntax: the raw IEEE-754 bits of the double.
fn fconst(v: f64) -> String {
    format!("0x{:016X}", v.to_bits())
}

/// Tag values understood by the runtime's `pyrs_print_list` and
/// `pyrs_list_contains`. Scalars are 0-3; a list element encodes its own
/// element tag recursively as `4 + 8 * inner`, so `list[list[int]]`
/// elements carry tag 4 and the runtime recurses.
fn elem_tag(ty: &Ty) -> u32 {
    match ty {
        Ty::Int => 0,
        Ty::Float => 1,
        Ty::Bool => 2,
        Ty::Str => 3,
        Ty::List(inner) => 4 + 8 * elem_tag(inner),
        Ty::File | Ty::None => unreachable!("no print tag for {ty:?}"),
    }
}

fn escape_bytes(s: &str) -> (String, usize) {
    let mut out = String::new();
    let bytes = s.as_bytes();
    for &b in bytes {
        if (0x20..0x7f).contains(&b) && b != b'"' && b != b'\\' {
            out.push(b as char);
        } else {
            write!(out, "\\{b:02X}").unwrap();
        }
    }
    out.push_str("\\00");
    (out, bytes.len() + 1)
}

#[derive(Default)]
struct Emitter {
    /// finished function definitions
    funcs: String,
    /// body of the function currently being emitted
    body: String,
    /// interned string constants: content → global name
    strings: HashMap<String, String>,
    string_defs: String,
    /// module-level variable definitions (@g.<name>)
    global_defs: String,
    tmp: usize,
    blk: usize,
    cur_block: String,
    terminated: bool,
    /// (continue target, break target) for enclosing loops
    loops: Vec<(String, String)>,
}

impl Emitter {
    fn finish(self) -> String {
        let mut out = String::new();
        out.push_str("; generated by pyrs\n\n");
        out.push_str("declare void @pyrs_print_int(i64)\n");
        out.push_str("declare void @pyrs_print_float(double)\n");
        out.push_str("declare void @pyrs_print_bool(i32)\n");
        out.push_str("declare void @pyrs_print_str(ptr)\n");
        out.push_str("declare void @pyrs_print_list(ptr, i32)\n");
        out.push_str("declare void @pyrs_print_sep()\n");
        out.push_str("declare void @pyrs_print_end()\n");
        out.push_str("declare void @pyrs_die(ptr)\n");
        out.push_str("declare ptr @pyrs_str_concat(ptr, ptr)\n");
        out.push_str("declare ptr @pyrs_str_repeat(ptr, i64)\n");
        out.push_str("declare i32 @pyrs_str_cmp(ptr, ptr)\n");
        out.push_str("declare ptr @pyrs_str_index(ptr, i64)\n");
        out.push_str("declare ptr @pyrs_str_from_int(i64)\n");
        out.push_str("declare ptr @pyrs_str_from_float(double)\n");
        out.push_str("declare ptr @pyrs_str_from_bool(i32)\n");
        out.push_str("declare ptr @pyrs_str_slice(ptr, i64, i64, i64)\n");
        out.push_str("declare i32 @pyrs_str_contains(ptr, ptr)\n");
        out.push_str("declare ptr @pyrs_str_upper(ptr)\n");
        out.push_str("declare ptr @pyrs_str_lower(ptr)\n");
        out.push_str("declare ptr @pyrs_str_strip(ptr)\n");
        out.push_str("declare ptr @pyrs_str_lstrip(ptr)\n");
        out.push_str("declare ptr @pyrs_str_rstrip(ptr)\n");
        out.push_str("declare i32 @pyrs_str_startswith(ptr, ptr)\n");
        out.push_str("declare i32 @pyrs_str_endswith(ptr, ptr)\n");
        out.push_str("declare i64 @pyrs_str_find(ptr, ptr)\n");
        out.push_str("declare i64 @pyrs_str_count(ptr, ptr)\n");
        out.push_str("declare ptr @pyrs_str_replace(ptr, ptr, ptr)\n");
        out.push_str("declare ptr @pyrs_str_split_ws(ptr)\n");
        out.push_str("declare ptr @pyrs_str_split(ptr, ptr)\n");
        out.push_str("declare ptr @pyrs_str_join(ptr, ptr)\n");
        out.push_str("declare ptr @pyrs_list_new(i64)\n");
        out.push_str("declare void @pyrs_list_push(ptr, i64)\n");
        out.push_str("declare ptr @pyrs_list_slice(ptr, i64, i64, i64)\n");
        out.push_str("declare i32 @pyrs_list_contains(ptr, i64, i32)\n");
        out.push_str("declare i64 @pyrs_list_pop(ptr, i64)\n");
        out.push_str("declare ptr @pyrs_input(ptr)\n");
        out.push_str("declare ptr @pyrs_argv()\n");
        out.push_str("declare void @pyrs_set_args(i32, ptr)\n");
        out.push_str("declare ptr @pyrs_open(ptr, ptr)\n");
        out.push_str("declare ptr @pyrs_file_read(ptr)\n");
        out.push_str("declare ptr @pyrs_file_readline(ptr)\n");
        out.push_str("declare ptr @pyrs_file_readlines(ptr)\n");
        out.push_str("declare i64 @pyrs_file_write(ptr, ptr)\n");
        out.push_str("declare void @pyrs_file_close(ptr)\n");
        out.push_str("declare i64 @pyrs_ipow(i64, i64)\n");
        out.push_str("declare double @pyrs_ffloordiv(double, double)\n");
        out.push_str("declare double @pyrs_fmod_floored(double, double)\n");
        out.push_str("declare double @llvm.fabs.f64(double)\n");
        out.push_str("declare double @llvm.floor.f64(double)\n");
        out.push_str("declare double @llvm.pow.f64(double, double)\n");
        out.push_str("declare i64 @llvm.fptosi.sat.i64.f64(double)\n\n");
        out.push_str(&self.global_defs);
        out.push_str(&self.string_defs);
        out.push('\n');
        out.push_str(&self.funcs);
        out
    }

    fn emit_module(&mut self, module: &Module) {
        // module globals, zero/null-initialized; assigned when the entry
        // function runs its top-level statements
        for (name, ty) in &module.globals {
            let init = match ty {
                Ty::Float => fconst(0.0),
                Ty::Bool => "false".to_string(),
                Ty::Str | Ty::List(_) | Ty::File => "null".to_string(),
                _ => "0".to_string(),
            };
            self.global_defs.push_str(&format!(
                "@g.{name} = internal global {} {init}\n",
                lty(*ty)
            ));
        }
        for func in &module.funcs {
            self.emit_function(func);
        }
        // the real C main: call the entry function and exit 0
        let entry = mangle(&module.entry);
        self.funcs.push_str(&format!(
            "define i32 @main(i32 %argc, ptr %argv) {{\nentry:\n  \
             call void @pyrs_set_args(i32 %argc, ptr %argv)\n  \
             call void @{entry}()\n  ret i32 0\n}}\n\n"
        ));
    }

    // ---- low-level helpers ----

    fn line(&mut self, s: impl AsRef<str>) {
        self.body.push_str("  ");
        self.body.push_str(s.as_ref());
        self.body.push('\n');
    }

    fn tmp(&mut self) -> String {
        self.tmp += 1;
        format!("%t{}", self.tmp)
    }

    fn fresh_block(&mut self, hint: &str) -> String {
        self.blk += 1;
        format!("{hint}.{}", self.blk)
    }

    fn start_block(&mut self, label: &str) {
        self.body.push_str(label);
        self.body.push_str(":\n");
        self.cur_block = label.to_string();
        self.terminated = false;
    }

    /// A string constant as a `{ i64 len, [n x i8] }` global; the pointer
    /// doubles as the runtime `PyrsStr*`.
    fn intern_string(&mut self, content: &str) -> String {
        if let Some(name) = self.strings.get(content) {
            return name.clone();
        }
        let name = format!("@.str.{}", self.strings.len());
        let (escaped, storage) = escape_bytes(content);
        let len = content.len();
        self.string_defs.push_str(&format!(
            "{name} = private unnamed_addr constant {{ i64, [{storage} x i8] }} \
             {{ i64 {len}, [{storage} x i8] c\"{escaped}\" }}\n"
        ));
        self.strings.insert(content.to_string(), name.clone());
        name
    }

    /// Trap like the runtime's check_ref when a str/list local is still
    /// null (read before assignment).
    fn emit_ref_check(&mut self, ptr: &str) {
        let is_null = self.tmp();
        self.line(format!("{is_null} = icmp eq ptr {ptr}, null"));
        let trap_l = self.fresh_block("null.trap");
        let ok_l = self.fresh_block("null.ok");
        self.line(format!("br i1 {is_null}, label %{trap_l}, label %{ok_l}"));
        self.start_block(&trap_l);
        self.emit_die("UnboundLocalError: value used before assignment");
        self.start_block(&ok_l);
    }

    /// str and list both lead with an i64 length; load it inline.
    fn emit_len(&mut self, ptr: &str) -> String {
        self.emit_ref_check(ptr);
        let t = self.tmp();
        self.line(format!("{t} = load i64, ptr {ptr}"));
        t
    }

    /// Inline list element addressing: negative-index adjustment, bounds
    /// check (trapping with `message`), then the slot address. Much faster
    /// than an out-of-line runtime call in hot loops.
    fn emit_list_elem_addr(&mut self, hdr: &str, index: &str, message: &str) -> String {
        let len = self.emit_len(hdr);
        let neg = self.tmp();
        self.line(format!("{neg} = icmp slt i64 {index}, 0"));
        let plus = self.tmp();
        self.line(format!("{plus} = add i64 {index}, {len}"));
        let adj = self.tmp();
        self.line(format!("{adj} = select i1 {neg}, i64 {plus}, i64 {index}"));
        let below = self.tmp();
        self.line(format!("{below} = icmp slt i64 {adj}, 0"));
        let above = self.tmp();
        self.line(format!("{above} = icmp sge i64 {adj}, {len}"));
        let oob = self.tmp();
        self.line(format!("{oob} = or i1 {below}, {above}"));
        let trap_l = self.fresh_block("idx.trap");
        let ok_l = self.fresh_block("idx.ok");
        self.line(format!("br i1 {oob}, label %{trap_l}, label %{ok_l}"));
        self.start_block(&trap_l);
        self.emit_die(message);
        self.start_block(&ok_l);
        // PyrsList layout: { i64 len; i64 cap; i64* data } — data at +16
        let data_pp = self.tmp();
        self.line(format!(
            "{data_pp} = getelementptr inbounds i8, ptr {hdr}, i64 16"
        ));
        let data_p = self.tmp();
        self.line(format!("{data_p} = load ptr, ptr {data_pp}"));
        let addr = self.tmp();
        self.line(format!(
            "{addr} = getelementptr inbounds i64, ptr {data_p}, i64 {adj}"
        ));
        addr
    }

    /// Trap with `message` and mark the block terminated.
    fn emit_die(&mut self, message: &str) {
        let msg = self.intern_string(message);
        // pyrs_die takes a plain C string: skip the 8-byte length header
        self.line(format!(
            "call void @pyrs_die(ptr getelementptr inbounds (i8, ptr {msg}, i64 8))"
        ));
        self.line("unreachable");
        self.terminated = true;
    }

    // ---- value slots (8-byte list elements) ----

    fn slot_from_value(&mut self, value: &str, ty: Ty) -> String {
        match ty {
            Ty::Int => value.to_string(),
            Ty::Float => {
                let t = self.tmp();
                self.line(format!("{t} = bitcast double {value} to i64"));
                t
            }
            Ty::Bool => {
                let t = self.tmp();
                self.line(format!("{t} = zext i1 {value} to i64"));
                t
            }
            Ty::Str | Ty::List(_) => {
                let t = self.tmp();
                self.line(format!("{t} = ptrtoint ptr {value} to i64"));
                t
            }
            other => unreachable!("no slot representation for {other:?}"),
        }
    }

    fn value_from_slot(&mut self, slot: &str, ty: Ty) -> String {
        match ty {
            Ty::Int => slot.to_string(),
            Ty::Float => {
                let t = self.tmp();
                self.line(format!("{t} = bitcast i64 {slot} to double"));
                t
            }
            Ty::Bool => {
                let t = self.tmp();
                self.line(format!("{t} = trunc i64 {slot} to i1"));
                t
            }
            Ty::Str | Ty::List(_) => {
                let t = self.tmp();
                self.line(format!("{t} = inttoptr i64 {slot} to ptr"));
                t
            }
            other => unreachable!("no slot representation for {other:?}"),
        }
    }

    // ---- functions ----

    fn emit_function(&mut self, func: &Function) {
        self.body.clear();
        self.tmp = 0;
        self.blk = 0;
        self.loops.clear();

        self.start_block("entry");
        // spill params into allocas so assignment to params just works
        for (name, ty) in &func.params {
            self.line(format!("%v.{name} = alloca {}", lty(*ty)));
            self.line(format!("store {} %p.{name}, ptr %v.{name}", lty(*ty)));
        }
        // all locals up front, zero/null-initialized (a conditionally
        // assigned variable reads as 0/0.0/False/null instead of being UB;
        // the runtime traps on null str/list use)
        for (name, ty) in &func.locals {
            self.line(format!("%v.{name} = alloca {}", lty(*ty)));
            let zero = match ty {
                Ty::Float => fconst(0.0),
                Ty::Str | Ty::List(_) | Ty::File => "null".to_string(),
                _ => "0".to_string(),
            };
            self.line(format!("store {} {zero}, ptr %v.{name}", lty(*ty)));
        }

        self.emit_block(&func.body);

        if !self.terminated {
            if func.ret == Ty::None {
                self.line("ret void");
            } else {
                // semantic proved all paths return; this block is unreachable
                self.line("unreachable");
            }
        }

        let params = func
            .params
            .iter()
            .map(|(name, ty)| format!("{} %p.{name}", lty(*ty)))
            .collect::<Vec<_>>()
            .join(", ");
        self.funcs.push_str(&format!(
            "define {} @{}({params}) {{\n{}}}\n\n",
            lty(func.ret),
            mangle(&func.name),
            self.body
        ));
    }

    fn emit_block(&mut self, stmts: &[Stmt]) {
        for stmt in stmts {
            if self.terminated {
                // code after return/break/continue is unreachable; drop it
                break;
            }
            self.emit_stmt(stmt);
        }
    }

    fn emit_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Assign { name, value } => {
                let v = self.emit_expr(value);
                self.line(format!("store {} {v}, ptr %v.{name}", lty(value.ty)));
            }
            Stmt::GlobalAssign { name, value } => {
                let v = self.emit_expr(value);
                self.line(format!("store {} {v}, ptr @g.{name}", lty(value.ty)));
            }
            Stmt::IndexAssign { base, index, value } => {
                let b = self.emit_expr(base);
                let i = self.emit_expr(index);
                let v = self.emit_expr(value);
                let slot = self.slot_from_value(&v, value.ty);
                let addr = self.emit_list_elem_addr(
                    &b,
                    &i,
                    "IndexError: list assignment index out of range",
                );
                self.line(format!("store i64 {slot}, ptr {addr}"));
            }
            Stmt::ListAppend { list, value } => {
                let l = self.emit_expr(list);
                let v = self.emit_expr(value);
                let slot = self.slot_from_value(&v, value.ty);
                self.line(format!("call void @pyrs_list_push(ptr {l}, i64 {slot})"));
            }
            Stmt::ListAppendUnchecked { list, value } => {
                // capacity was guaranteed at allocation: store the slot at
                // data[len] and bump len, no call, no check
                let l = self.emit_expr(list);
                let v = self.emit_expr(value);
                let slot = self.slot_from_value(&v, value.ty);
                let len = self.tmp();
                self.line(format!("{len} = load i64, ptr {l}"));
                let data_pp = self.tmp();
                self.line(format!(
                    "{data_pp} = getelementptr inbounds i8, ptr {l}, i64 16"
                ));
                let data_p = self.tmp();
                self.line(format!("{data_p} = load ptr, ptr {data_pp}"));
                let addr = self.tmp();
                self.line(format!(
                    "{addr} = getelementptr inbounds i64, ptr {data_p}, i64 {len}"
                ));
                self.line(format!("store i64 {slot}, ptr {addr}"));
                let newlen = self.tmp();
                self.line(format!("{newlen} = add i64 {len}, 1"));
                self.line(format!("store i64 {newlen}, ptr {l}"));
            }
            Stmt::Return(None) => {
                self.line("ret void");
                self.terminated = true;
            }
            Stmt::Return(Some(value)) => {
                let v = self.emit_expr(value);
                self.line(format!("ret {} {v}", lty(value.ty)));
                self.terminated = true;
            }
            Stmt::ExprStmt(expr) => {
                self.emit_expr(expr);
            }
            Stmt::Die(message) => {
                self.emit_die(message);
            }
            Stmt::Print(args) => {
                for (i, arg) in args.iter().enumerate() {
                    if i > 0 {
                        self.line("call void @pyrs_print_sep()");
                    }
                    let v = self.emit_expr(arg);
                    match arg.ty {
                        Ty::Int => self.line(format!("call void @pyrs_print_int(i64 {v})")),
                        Ty::Float => self.line(format!("call void @pyrs_print_float(double {v})")),
                        Ty::Bool => {
                            let ext = self.tmp();
                            self.line(format!("{ext} = zext i1 {v} to i32"));
                            self.line(format!("call void @pyrs_print_bool(i32 {ext})"));
                        }
                        Ty::Str => self.line(format!("call void @pyrs_print_str(ptr {v})")),
                        Ty::List(elem) => self.line(format!(
                            "call void @pyrs_print_list(ptr {v}, i32 {})",
                            elem_tag(elem)
                        )),
                        Ty::File | Ty::None => {
                            unreachable!("semantic rejects {:?} print args", arg.ty)
                        }
                    }
                }
                self.line("call void @pyrs_print_end()");
            }
            Stmt::Break => {
                let (_, end) = self.loops.last().expect("break outside loop").clone();
                self.line(format!("br label %{end}"));
                self.terminated = true;
            }
            Stmt::Continue => {
                let (cont, _) = self.loops.last().expect("continue outside loop").clone();
                self.line(format!("br label %{cont}"));
                self.terminated = true;
            }
            Stmt::While { cond, body, step } => {
                let cond_l = self.fresh_block("while.cond");
                let body_l = self.fresh_block("while.body");
                let step_l = self.fresh_block("while.step");
                let end_l = self.fresh_block("while.end");

                self.line(format!("br label %{cond_l}"));
                self.start_block(&cond_l);
                let c = self.emit_expr(cond);
                self.line(format!("br i1 {c}, label %{body_l}, label %{end_l}"));

                self.start_block(&body_l);
                // continue jumps to the step block (for-loop increment)
                self.loops.push((step_l.clone(), end_l.clone()));
                self.emit_block(body);
                self.loops.pop();
                if !self.terminated {
                    self.line(format!("br label %{step_l}"));
                }

                self.start_block(&step_l);
                self.emit_block(step);
                self.line(format!("br label %{cond_l}"));

                self.start_block(&end_l);
            }
            Stmt::If { branches, orelse } => {
                let end_l = self.fresh_block("if.end");
                let mut else_l = String::new();

                for (i, (cond, body)) in branches.iter().enumerate() {
                    let then_l = self.fresh_block("if.then");
                    let last = i + 1 == branches.len();
                    let next_l = if last && orelse.is_empty() {
                        end_l.clone()
                    } else {
                        self.fresh_block("if.else")
                    };

                    let c = self.emit_expr(cond);
                    self.line(format!("br i1 {c}, label %{then_l}, label %{next_l}"));

                    self.start_block(&then_l);
                    self.emit_block(body);
                    if !self.terminated {
                        self.line(format!("br label %{end_l}"));
                    }

                    self.start_block(&next_l);
                    else_l = next_l;
                }

                if !orelse.is_empty() {
                    // current block is the final else
                    debug_assert_eq!(self.cur_block, else_l);
                    self.emit_block(orelse);
                    if !self.terminated {
                        self.line(format!("br label %{end_l}"));
                    }
                    self.start_block(&end_l);
                }
                // when orelse is empty the last `next_l` *is* end_l and is
                // already started
            }
        }
    }

    // ---- expressions ----

    /// Emit code for `expr`; returns the LLVM value (a temp or a constant).
    fn emit_expr(&mut self, expr: &Expr) -> String {
        match &expr.kind {
            ExprKind::ConstInt(v) => v.to_string(),
            ExprKind::ConstFloat(v) => fconst(*v),
            ExprKind::ConstBool(v) => v.to_string(),
            ExprKind::ConstStr(s) => self.intern_string(s),
            ExprKind::Local(name) => {
                let t = self.tmp();
                self.line(format!("{t} = load {}, ptr %v.{name}", lty(expr.ty)));
                t
            }
            ExprKind::GlobalLoad(name) => {
                let t = self.tmp();
                self.line(format!("{t} = load {}, ptr @g.{name}", lty(expr.ty)));
                t
            }
            ExprKind::Input { prompt } => {
                let p = match prompt {
                    Some(e) => self.emit_expr(e),
                    Option::None => "null".to_string(),
                };
                let t = self.tmp();
                self.line(format!("{t} = call ptr @pyrs_input(ptr {p})"));
                t
            }
            ExprKind::Argv => {
                let t = self.tmp();
                self.line(format!("{t} = call ptr @pyrs_argv()"));
                t
            }
            ExprKind::Open { path, mode } => {
                let p = self.emit_expr(path);
                let m = self.emit_expr(mode);
                let t = self.tmp();
                self.line(format!("{t} = call ptr @pyrs_open(ptr {p}, ptr {m})"));
                t
            }
            ExprKind::FileCall { func, args } => {
                let vals: Vec<String> = args.iter().map(|a| self.emit_expr(a)).collect();
                let args_str = vals
                    .iter()
                    .map(|v| format!("ptr {v}"))
                    .collect::<Vec<_>>()
                    .join(", ");
                match func {
                    FileFn::Read | FileFn::ReadLine | FileFn::ReadLines => {
                        let callee = match func {
                            FileFn::Read => "pyrs_file_read",
                            FileFn::ReadLine => "pyrs_file_readline",
                            _ => "pyrs_file_readlines",
                        };
                        let t = self.tmp();
                        self.line(format!("{t} = call ptr @{callee}({args_str})"));
                        t
                    }
                    FileFn::Write => {
                        let t = self.tmp();
                        self.line(format!("{t} = call i64 @pyrs_file_write({args_str})"));
                        t
                    }
                    FileFn::Close => {
                        self.line(format!("call void @pyrs_file_close({args_str})"));
                        String::new()
                    }
                }
            }
            ExprKind::Let { name, value, body } => {
                let v = self.emit_expr(value);
                self.line(format!("store {} {v}, ptr %v.{name}", lty(value.ty)));
                self.emit_expr(body)
            }
            ExprKind::Call { func, args } => {
                let mut arg_list = Vec::new();
                for arg in args {
                    let v = self.emit_expr(arg);
                    arg_list.push(format!("{} {v}", lty(arg.ty)));
                }
                let args_str = arg_list.join(", ");
                let callee = mangle(func);
                if expr.ty == Ty::None {
                    self.line(format!("call void @{callee}({args_str})"));
                    String::new()
                } else {
                    let t = self.tmp();
                    self.line(format!("{t} = call {} @{callee}({args_str})", lty(expr.ty)));
                    t
                }
            }
            ExprKind::Index { base, index } => {
                let b = self.emit_expr(base);
                let i = self.emit_expr(index);
                match base.ty {
                    Ty::Str => {
                        let t = self.tmp();
                        self.line(format!("{t} = call ptr @pyrs_str_index(ptr {b}, i64 {i})"));
                        t
                    }
                    Ty::List(elem) => {
                        let addr =
                            self.emit_list_elem_addr(&b, &i, "IndexError: list index out of range");
                        let slot = self.tmp();
                        self.line(format!("{slot} = load i64, ptr {addr}"));
                        self.value_from_slot(&slot, *elem)
                    }
                    other => unreachable!("index on {other:?}"),
                }
            }
            ExprKind::Slice { base, lo, hi, step } => {
                let b = self.emit_expr(base);
                let lo_v = self.emit_expr(lo);
                let hi_v = self.emit_expr(hi);
                let step_v = self.emit_expr(step);
                let callee = match base.ty {
                    Ty::Str => "pyrs_str_slice",
                    Ty::List(_) => "pyrs_list_slice",
                    other => unreachable!("slice on {other:?}"),
                };
                let t = self.tmp();
                self.line(format!(
                    "{t} = call ptr @{callee}(ptr {b}, i64 {lo_v}, i64 {hi_v}, i64 {step_v})"
                ));
                t
            }
            ExprKind::StrCall { func, args } => {
                let vals: Vec<String> = args.iter().map(|a| self.emit_expr(a)).collect();
                // (runtime symbol, returns i1-via-i32, returns i64)
                let (callee, is_bool, is_int) = match func {
                    StrFn::Upper => ("pyrs_str_upper", false, false),
                    StrFn::Lower => ("pyrs_str_lower", false, false),
                    StrFn::Strip => ("pyrs_str_strip", false, false),
                    StrFn::Lstrip => ("pyrs_str_lstrip", false, false),
                    StrFn::Rstrip => ("pyrs_str_rstrip", false, false),
                    StrFn::StartsWith => ("pyrs_str_startswith", true, false),
                    StrFn::EndsWith => ("pyrs_str_endswith", true, false),
                    StrFn::Find => ("pyrs_str_find", false, true),
                    StrFn::Count => ("pyrs_str_count", false, true),
                    StrFn::Replace => ("pyrs_str_replace", false, false),
                    StrFn::SplitWs => ("pyrs_str_split_ws", false, false),
                    StrFn::Split => ("pyrs_str_split", false, false),
                    StrFn::Join => ("pyrs_str_join", false, false),
                };
                let args_str = vals
                    .iter()
                    .map(|v| format!("ptr {v}"))
                    .collect::<Vec<_>>()
                    .join(", ");
                let t = self.tmp();
                if is_bool {
                    self.line(format!("{t} = call i32 @{callee}({args_str})"));
                    let b = self.tmp();
                    self.line(format!("{b} = icmp ne i32 {t}, 0"));
                    b
                } else if is_int {
                    self.line(format!("{t} = call i64 @{callee}({args_str})"));
                    t
                } else {
                    self.line(format!("{t} = call ptr @{callee}({args_str})"));
                    t
                }
            }
            ExprKind::Contains { needle, haystack } => {
                let n = self.emit_expr(needle);
                let h = self.emit_expr(haystack);
                let c = self.tmp();
                match haystack.ty {
                    Ty::Str => {
                        self.line(format!(
                            "{c} = call i32 @pyrs_str_contains(ptr {h}, ptr {n})"
                        ));
                    }
                    Ty::List(elem) => {
                        let slot = self.slot_from_value(&n, needle.ty);
                        self.line(format!(
                            "{c} = call i32 @pyrs_list_contains(ptr {h}, i64 {slot}, i32 {})",
                            elem_tag(elem)
                        ));
                    }
                    other => unreachable!("contains on {other:?}"),
                }
                let t = self.tmp();
                self.line(format!("{t} = icmp ne i32 {c}, 0"));
                t
            }
            ExprKind::ListPop { list, index } => {
                let l = self.emit_expr(list);
                let i = self.emit_expr(index);
                let slot = self.tmp();
                self.line(format!(
                    "{slot} = call i64 @pyrs_list_pop(ptr {l}, i64 {i})"
                ));
                self.value_from_slot(&slot, expr.ty)
            }
            ExprKind::ListLit(items) => {
                let l = self.tmp();
                self.line(format!(
                    "{l} = call ptr @pyrs_list_new(i64 {})",
                    items.len()
                ));
                for item in items {
                    let v = self.emit_expr(item);
                    let slot = self.slot_from_value(&v, item.ty);
                    self.line(format!("call void @pyrs_list_push(ptr {l}, i64 {slot})"));
                }
                l
            }
            ExprKind::ListNew { cap } => {
                let c = self.emit_expr(cap);
                let t = self.tmp();
                self.line(format!("{t} = call ptr @pyrs_list_new(i64 {c})"));
                t
            }
            ExprKind::Block { stmts, result } => {
                for stmt in stmts {
                    self.emit_stmt(stmt);
                }
                self.emit_expr(result)
            }
            ExprKind::Len(inner) => {
                let v = self.emit_expr(inner);
                self.emit_len(&v)
            }
            ExprKind::IntToFloat(inner) => {
                let v = self.emit_expr(inner);
                let t = self.tmp();
                self.line(format!("{t} = sitofp i64 {v} to double"));
                t
            }
            ExprKind::FloatToInt(inner) => {
                let v = self.emit_expr(inner);
                // Python raises on nan/inf instead of converting
                let is_nan = self.tmp();
                self.line(format!("{is_nan} = fcmp uno double {v}, {}", fconst(0.0)));
                let nan_l = self.fresh_block("toint.nan");
                let ok1_l = self.fresh_block("toint.num");
                self.line(format!("br i1 {is_nan}, label %{nan_l}, label %{ok1_l}"));
                self.start_block(&nan_l);
                self.emit_die("ValueError: cannot convert float NaN to integer");
                self.start_block(&ok1_l);
                let abs = self.tmp();
                self.line(format!("{abs} = call double @llvm.fabs.f64(double {v})"));
                let is_inf = self.tmp();
                self.line(format!(
                    "{is_inf} = fcmp oeq double {abs}, {}",
                    fconst(f64::INFINITY)
                ));
                let inf_l = self.fresh_block("toint.inf");
                let ok2_l = self.fresh_block("toint.ok");
                self.line(format!("br i1 {is_inf}, label %{inf_l}, label %{ok2_l}"));
                self.start_block(&inf_l);
                self.emit_die("OverflowError: cannot convert float infinity to integer");
                self.start_block(&ok2_l);
                let t = self.tmp();
                // saturating: still defined if the finite value exceeds i64
                self.line(format!(
                    "{t} = call i64 @llvm.fptosi.sat.i64.f64(double {v})"
                ));
                t
            }
            ExprKind::BoolToInt(inner) => {
                let v = self.emit_expr(inner);
                let t = self.tmp();
                self.line(format!("{t} = zext i1 {v} to i64"));
                t
            }
            ExprKind::IntToStr(inner) => {
                let v = self.emit_expr(inner);
                let t = self.tmp();
                self.line(format!("{t} = call ptr @pyrs_str_from_int(i64 {v})"));
                t
            }
            ExprKind::FloatToStr(inner) => {
                let v = self.emit_expr(inner);
                let t = self.tmp();
                self.line(format!("{t} = call ptr @pyrs_str_from_float(double {v})"));
                t
            }
            ExprKind::BoolToStr(inner) => {
                let v = self.emit_expr(inner);
                let ext = self.tmp();
                self.line(format!("{ext} = zext i1 {v} to i32"));
                let t = self.tmp();
                self.line(format!("{t} = call ptr @pyrs_str_from_bool(i32 {ext})"));
                t
            }
            ExprKind::ToBool(inner) => {
                let v = self.emit_expr(inner);
                match inner.ty {
                    Ty::Int => {
                        let t = self.tmp();
                        self.line(format!("{t} = icmp ne i64 {v}, 0"));
                        t
                    }
                    // une: NaN is truthy, like Python
                    Ty::Float => {
                        let t = self.tmp();
                        self.line(format!("{t} = fcmp une double {v}, {}", fconst(0.0)));
                        t
                    }
                    // str and list share the leading i64 length field
                    Ty::Str | Ty::List(_) => {
                        let len = self.emit_len(&v);
                        let t = self.tmp();
                        self.line(format!("{t} = icmp ne i64 {len}, 0"));
                        t
                    }
                    other => unreachable!("ToBool on {other:?}"),
                }
            }
            ExprKind::Unary { op, operand } => {
                let v = self.emit_expr(operand);
                let t = self.tmp();
                match (op, operand.ty) {
                    (UnOp::Neg, Ty::Int) => self.line(format!("{t} = sub i64 0, {v}")),
                    (UnOp::Neg, Ty::Float) => self.line(format!("{t} = fneg double {v}")),
                    (UnOp::Not, Ty::Bool) => self.line(format!("{t} = xor i1 {v}, true")),
                    other => unreachable!("bad unary op {other:?}"),
                }
                t
            }
            ExprKind::Binary { op, left, right } => self.emit_binary(*op, left, right),
        }
    }

    fn emit_binary(&mut self, op: BinOp, left: &Expr, right: &Expr) -> String {
        // short-circuit and/or need control flow, not plain instructions
        if matches!(op, BinOp::And | BinOp::Or) {
            return self.emit_short_circuit(op, left, right);
        }

        // string operations dispatch to the runtime
        if left.ty == Ty::Str {
            return self.emit_str_binary(op, left, right);
        }

        let l = self.emit_expr(left);
        let r = self.emit_expr(right);
        let ty = left.ty; // semantic guarantees both sides match

        match op {
            BinOp::Add | BinOp::Sub | BinOp::Mul => {
                let instr = match (op, ty) {
                    (BinOp::Add, Ty::Int) => "add",
                    (BinOp::Sub, Ty::Int) => "sub",
                    (BinOp::Mul, Ty::Int) => "mul",
                    (BinOp::Add, Ty::Float) => "fadd",
                    (BinOp::Sub, Ty::Float) => "fsub",
                    (BinOp::Mul, Ty::Float) => "fmul",
                    other => unreachable!("bad arith {other:?}"),
                };
                let t = self.tmp();
                self.line(format!("{t} = {instr} {} {l}, {r}", lty(ty)));
                t
            }
            BinOp::Pow => match ty {
                // repeated squaring in the runtime; negative exponent traps
                Ty::Int => {
                    let t = self.tmp();
                    self.line(format!("{t} = call i64 @pyrs_ipow(i64 {l}, i64 {r})"));
                    t
                }
                Ty::Float => {
                    // Python: 0.0 ** negative raises instead of returning inf
                    let zb = self.tmp();
                    self.line(format!("{zb} = fcmp oeq double {l}, {}", fconst(0.0)));
                    let ne = self.tmp();
                    self.line(format!("{ne} = fcmp olt double {r}, {}", fconst(0.0)));
                    let bad = self.tmp();
                    self.line(format!("{bad} = and i1 {zb}, {ne}"));
                    let trap_l = self.fresh_block("pow.trap");
                    let ok_l = self.fresh_block("pow.ok");
                    self.line(format!("br i1 {bad}, label %{trap_l}, label %{ok_l}"));
                    self.start_block(&trap_l);
                    self.emit_die("ZeroDivisionError: 0.0 cannot be raised to a negative power");
                    self.start_block(&ok_l);
                    let t = self.tmp();
                    self.line(format!(
                        "{t} = call double @llvm.pow.f64(double {l}, double {r})"
                    ));
                    t
                }
                other => unreachable!("pow on {other:?}"),
            },
            // true division: always float (semantic inserted the casts)
            BinOp::Div => {
                self.guard_zero(&r, Ty::Float, "ZeroDivisionError: division by zero");
                let t = self.tmp();
                self.line(format!("{t} = fdiv double {l}, {r}"));
                t
            }
            BinOp::FloorDiv => match ty {
                Ty::Int => {
                    self.guard_zero(&r, Ty::Int, "ZeroDivisionError: division by zero");
                    let safe_r = self.guard_int_min(&l, &r);
                    let (q, r0) = self.emit_divmod(&l, &safe_r);
                    let adj = self.emit_floor_adjust(&r0, &safe_r);
                    let adj64 = self.tmp();
                    self.line(format!("{adj64} = zext i1 {adj} to i64"));
                    let t = self.tmp();
                    self.line(format!("{t} = sub i64 {q}, {adj64}"));
                    t
                }
                Ty::Float => {
                    self.guard_zero(&r, Ty::Float, "ZeroDivisionError: division by zero");
                    // CPython float_divmod semantics live in the runtime
                    let t = self.tmp();
                    self.line(format!(
                        "{t} = call double @pyrs_ffloordiv(double {l}, double {r})"
                    ));
                    t
                }
                other => unreachable!("floordiv on {other:?}"),
            },
            BinOp::Mod => match ty {
                Ty::Int => {
                    self.guard_zero(&r, Ty::Int, "ZeroDivisionError: division by zero");
                    let safe_r = self.guard_int_min(&l, &r);
                    let r0 = self.tmp();
                    self.line(format!("{r0} = srem i64 {l}, {safe_r}"));
                    let adj = self.emit_floor_adjust(&r0, &safe_r);
                    let sel = self.tmp();
                    self.line(format!("{sel} = select i1 {adj}, i64 {safe_r}, i64 0"));
                    let t = self.tmp();
                    self.line(format!("{t} = add i64 {r0}, {sel}"));
                    t
                }
                Ty::Float => {
                    self.guard_zero(&r, Ty::Float, "ZeroDivisionError: division by zero");
                    // CPython float_divmod semantics live in the runtime
                    let t = self.tmp();
                    self.line(format!(
                        "{t} = call double @pyrs_fmod_floored(double {l}, double {r})"
                    ));
                    t
                }
                other => unreachable!("mod on {other:?}"),
            },
            BinOp::Eq | BinOp::Ne | BinOp::Lt | BinOp::Le | BinOp::Gt | BinOp::Ge => {
                let t = self.tmp();
                match ty {
                    Ty::Int => {
                        let cc = match op {
                            BinOp::Eq => "eq",
                            BinOp::Ne => "ne",
                            BinOp::Lt => "slt",
                            BinOp::Le => "sle",
                            BinOp::Gt => "sgt",
                            BinOp::Ge => "sge",
                            _ => unreachable!(),
                        };
                        self.line(format!("{t} = icmp {cc} i64 {l}, {r}"));
                    }
                    Ty::Float => {
                        // ordered except Ne: Python nan != x is True
                        let cc = match op {
                            BinOp::Eq => "oeq",
                            BinOp::Ne => "une",
                            BinOp::Lt => "olt",
                            BinOp::Le => "ole",
                            BinOp::Gt => "ogt",
                            BinOp::Ge => "oge",
                            _ => unreachable!(),
                        };
                        self.line(format!("{t} = fcmp {cc} double {l}, {r}"));
                    }
                    other => unreachable!("comparison on {other:?}"),
                }
                t
            }
            BinOp::And | BinOp::Or => unreachable!("handled above"),
        }
    }

    /// Binary ops whose left operand is a string.
    fn emit_str_binary(&mut self, op: BinOp, left: &Expr, right: &Expr) -> String {
        let l = self.emit_expr(left);
        let r = self.emit_expr(right);
        match op {
            BinOp::Add => {
                let t = self.tmp();
                self.line(format!("{t} = call ptr @pyrs_str_concat(ptr {l}, ptr {r})"));
                t
            }
            // semantic normalizes the int count to the right operand
            BinOp::Mul => {
                let t = self.tmp();
                self.line(format!("{t} = call ptr @pyrs_str_repeat(ptr {l}, i64 {r})"));
                t
            }
            BinOp::Eq | BinOp::Ne | BinOp::Lt | BinOp::Le | BinOp::Gt | BinOp::Ge => {
                let c = self.tmp();
                self.line(format!("{c} = call i32 @pyrs_str_cmp(ptr {l}, ptr {r})"));
                let cc = match op {
                    BinOp::Eq => "eq",
                    BinOp::Ne => "ne",
                    BinOp::Lt => "slt",
                    BinOp::Le => "sle",
                    BinOp::Gt => "sgt",
                    BinOp::Ge => "sge",
                    _ => unreachable!(),
                };
                let t = self.tmp();
                self.line(format!("{t} = icmp {cc} i32 {c}, 0"));
                t
            }
            other => unreachable!("bad str op {other:?}"),
        }
    }

    fn emit_short_circuit(&mut self, op: BinOp, left: &Expr, right: &Expr) -> String {
        let rhs_l = self.fresh_block("sc.rhs");
        let end_l = self.fresh_block("sc.end");

        let l = self.emit_expr(left);
        let lhs_block = self.cur_block.clone();
        let (skip_value, on_true, on_false) = match op {
            // a and b: if a is false, skip rhs and produce false
            BinOp::And => ("false", rhs_l.clone(), end_l.clone()),
            // a or b: if a is true, skip rhs and produce true
            BinOp::Or => ("true", end_l.clone(), rhs_l.clone()),
            _ => unreachable!(),
        };
        self.line(format!("br i1 {l}, label %{on_true}, label %{on_false}"));

        self.start_block(&rhs_l);
        let r = self.emit_expr(right);
        let rhs_block = self.cur_block.clone();
        self.line(format!("br label %{end_l}"));

        self.start_block(&end_l);
        let t = self.tmp();
        self.line(format!(
            "{t} = phi i1 [ {skip_value}, %{lhs_block} ], [ {r}, %{rhs_block} ]"
        ));
        t
    }

    /// Trap with a ZeroDivisionError when the divisor is zero.
    fn guard_zero(&mut self, divisor: &str, ty: Ty, message: &str) {
        let is_zero = self.tmp();
        match ty {
            Ty::Int => self.line(format!("{is_zero} = icmp eq i64 {divisor}, 0")),
            Ty::Float => self.line(format!(
                "{is_zero} = fcmp oeq double {divisor}, {}",
                fconst(0.0)
            )),
            other => unreachable!("guard_zero on {other:?}"),
        }
        let trap_l = self.fresh_block("div.trap");
        let ok_l = self.fresh_block("div.ok");
        self.line(format!("br i1 {is_zero}, label %{trap_l}, label %{ok_l}"));
        self.start_block(&trap_l);
        self.emit_die(message);
        self.start_block(&ok_l);
    }

    /// `i64::MIN / -1` overflows (UB in sdiv/srem). Substitute divisor 1 in
    /// exactly that case: MIN/1 = MIN matches two's-complement wrapping and
    /// the remainder is 0, branch-free.
    fn guard_int_min(&mut self, dividend: &str, divisor: &str) -> String {
        let is_min = self.tmp();
        self.line(format!(
            "{is_min} = icmp eq i64 {dividend}, -9223372036854775808"
        ));
        let is_neg1 = self.tmp();
        self.line(format!("{is_neg1} = icmp eq i64 {divisor}, -1"));
        let overflow = self.tmp();
        self.line(format!("{overflow} = and i1 {is_min}, {is_neg1}"));
        let safe = self.tmp();
        self.line(format!(
            "{safe} = select i1 {overflow}, i64 1, i64 {divisor}"
        ));
        safe
    }

    fn emit_divmod(&mut self, l: &str, r: &str) -> (String, String) {
        let q = self.tmp();
        self.line(format!("{q} = sdiv i64 {l}, {r}"));
        let rem = self.tmp();
        self.line(format!("{rem} = srem i64 {l}, {r}"));
        (q, rem)
    }

    /// True when the truncated result must be adjusted for floored
    /// semantics: remainder nonzero and its sign differs from the divisor's.
    fn emit_floor_adjust(&mut self, rem: &str, divisor: &str) -> String {
        let rnz = self.tmp();
        self.line(format!("{rnz} = icmp ne i64 {rem}, 0"));
        let x = self.tmp();
        self.line(format!("{x} = xor i64 {rem}, {divisor}"));
        let sgn = self.tmp();
        self.line(format!("{sgn} = icmp slt i64 {x}, 0"));
        let adj = self.tmp();
        self.line(format!("{adj} = and i1 {rnz}, {sgn}"));
        adj
    }
}
