//! Lowers the typed IR to LLVM IR in its textual format.
//!
//! The textual IR is the serialization boundary handed to the C++ shim,
//! which parses, verifies, optimizes and emits native object code.
//!
//! Semantics preserved from Python:
//! - `//` and `%` use floored division (result sign follows the divisor)
//! - division by zero traps with a ZeroDivisionError message instead of UB
//! - `int(float)` is a saturating conversion (no UB on NaN/overflow)
//! - `i64::MIN // -1` wraps instead of being UB (select on the divisor)
//!
//! All user symbols are prefixed `pyrs_` so they can never collide with
//! libc symbols (a user function named `printf` is fine).

use std::collections::HashMap;
use std::fmt::Write;

use ir::{BinOp, Expr, ExprKind, Function, Module, Stmt, Ty, UnOp};

pub fn emit_llvm_ir(module: &Module) -> String {
    let mut e = Emitter::default();
    e.emit_module(module);
    e.finish()
}

fn lty(ty: Ty) -> &'static str {
    match ty {
        Ty::Int => "i64",
        Ty::Float => "double",
        Ty::Bool => "i1",
        Ty::Str => "ptr",
        Ty::None => "void",
    }
}

fn mangle(name: &str) -> String {
    format!("pyrs_{name}")
}

/// LLVM hexadecimal float syntax: the raw IEEE-754 bits of the double.
fn fconst(v: f64) -> String {
    format!("0x{:016X}", v.to_bits())
}

fn escape_bytes(s: &str) -> (String, usize) {
    let mut out = String::new();
    let bytes = s.as_bytes();
    for &b in bytes {
        if (0x20..0x7f).contains(&b) && b != b'"' && b != b'\\' {
            out.push(b as char);
        } else {
            write!(out, "\\{b:02X}").unwrap();
        }
    }
    out.push_str("\\00");
    (out, bytes.len() + 1)
}

#[derive(Default)]
struct Emitter {
    /// finished function definitions
    funcs: String,
    /// body of the function currently being emitted
    body: String,
    /// interned string constants: content → global name
    strings: HashMap<String, String>,
    string_defs: String,
    tmp: usize,
    blk: usize,
    cur_block: String,
    terminated: bool,
    /// (continue target, break target) for enclosing loops
    loops: Vec<(String, String)>,
}

impl Emitter {
    fn finish(self) -> String {
        let mut out = String::new();
        out.push_str("; generated by pyrs\n\n");
        out.push_str("declare void @pyrs_print_int(i64)\n");
        out.push_str("declare void @pyrs_print_float(double)\n");
        out.push_str("declare void @pyrs_print_bool(i32)\n");
        out.push_str("declare void @pyrs_print_str(ptr)\n");
        out.push_str("declare void @pyrs_print_sep()\n");
        out.push_str("declare void @pyrs_print_end()\n");
        out.push_str("declare void @pyrs_die(ptr)\n");
        out.push_str("declare double @llvm.floor.f64(double)\n");
        out.push_str("declare i64 @llvm.fptosi.sat.i64.f64(double)\n\n");
        out.push_str(&self.string_defs);
        out.push('\n');
        out.push_str(&self.funcs);
        out
    }

    fn emit_module(&mut self, module: &Module) {
        for func in &module.funcs {
            self.emit_function(func);
        }
        // the real C main: call the entry function and exit 0
        let entry = mangle(&module.entry);
        self.funcs.push_str(&format!(
            "define i32 @main() {{\nentry:\n  call void @{entry}()\n  ret i32 0\n}}\n\n"
        ));
    }

    // ---- low-level helpers ----

    fn line(&mut self, s: impl AsRef<str>) {
        self.body.push_str("  ");
        self.body.push_str(s.as_ref());
        self.body.push('\n');
    }

    fn tmp(&mut self) -> String {
        self.tmp += 1;
        format!("%t{}", self.tmp)
    }

    fn fresh_block(&mut self, hint: &str) -> String {
        self.blk += 1;
        format!("{hint}.{}", self.blk)
    }

    fn start_block(&mut self, label: &str) {
        self.body.push_str(label);
        self.body.push_str(":\n");
        self.cur_block = label.to_string();
        self.terminated = false;
    }

    fn intern_string(&mut self, content: &str) -> String {
        if let Some(name) = self.strings.get(content) {
            return name.clone();
        }
        let name = format!("@.str.{}", self.strings.len());
        let (escaped, len) = escape_bytes(content);
        self.string_defs.push_str(&format!(
            "{name} = private unnamed_addr constant [{len} x i8] c\"{escaped}\"\n"
        ));
        self.strings.insert(content.to_string(), name.clone());
        name
    }

    // ---- functions ----

    fn emit_function(&mut self, func: &Function) {
        self.body.clear();
        self.tmp = 0;
        self.blk = 0;
        self.loops.clear();

        self.start_block("entry");
        // spill params into allocas so assignment to params just works
        for (name, ty) in &func.params {
            self.line(format!("%v.{name} = alloca {}", lty(*ty)));
            self.line(format!("store {} %p.{name}, ptr %v.{name}", lty(*ty)));
        }
        // all locals up front, zero-initialized (a conditionally-assigned
        // variable reads as 0/0.0/False instead of being UB)
        for (name, ty) in &func.locals {
            self.line(format!("%v.{name} = alloca {}", lty(*ty)));
            let zero = match ty {
                Ty::Float => fconst(0.0),
                _ => "0".to_string(),
            };
            self.line(format!("store {} {zero}, ptr %v.{name}", lty(*ty)));
        }

        self.emit_block(&func.body);

        if !self.terminated {
            if func.ret == Ty::None {
                self.line("ret void");
            } else {
                // semantic proved all paths return; this block is unreachable
                self.line("unreachable");
            }
        }

        let params = func
            .params
            .iter()
            .map(|(name, ty)| format!("{} %p.{name}", lty(*ty)))
            .collect::<Vec<_>>()
            .join(", ");
        self.funcs.push_str(&format!(
            "define {} @{}({params}) {{\n{}}}\n\n",
            lty(func.ret),
            mangle(&func.name),
            self.body
        ));
    }

    fn emit_block(&mut self, stmts: &[Stmt]) {
        for stmt in stmts {
            if self.terminated {
                // code after return/break/continue is unreachable; drop it
                break;
            }
            self.emit_stmt(stmt);
        }
    }

    fn emit_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Assign { name, value } => {
                let v = self.emit_expr(value);
                self.line(format!("store {} {v}, ptr %v.{name}", lty(value.ty)));
            }
            Stmt::Return(None) => {
                self.line("ret void");
                self.terminated = true;
            }
            Stmt::Return(Some(value)) => {
                let v = self.emit_expr(value);
                self.line(format!("ret {} {v}", lty(value.ty)));
                self.terminated = true;
            }
            Stmt::ExprStmt(expr) => {
                self.emit_expr(expr);
            }
            Stmt::Print(args) => {
                for (i, arg) in args.iter().enumerate() {
                    if i > 0 {
                        self.line("call void @pyrs_print_sep()");
                    }
                    let v = self.emit_expr(arg);
                    match arg.ty {
                        Ty::Int => self.line(format!("call void @pyrs_print_int(i64 {v})")),
                        Ty::Float => {
                            self.line(format!("call void @pyrs_print_float(double {v})"))
                        }
                        Ty::Bool => {
                            let ext = self.tmp();
                            self.line(format!("{ext} = zext i1 {v} to i32"));
                            self.line(format!("call void @pyrs_print_bool(i32 {ext})"));
                        }
                        Ty::Str => self.line(format!("call void @pyrs_print_str(ptr {v})")),
                        Ty::None => unreachable!("semantic rejects None print args"),
                    }
                }
                self.line("call void @pyrs_print_end()");
            }
            Stmt::Break => {
                let (_, end) = self.loops.last().expect("break outside loop").clone();
                self.line(format!("br label %{end}"));
                self.terminated = true;
            }
            Stmt::Continue => {
                let (cond, _) = self.loops.last().expect("continue outside loop").clone();
                self.line(format!("br label %{cond}"));
                self.terminated = true;
            }
            Stmt::While { cond, body } => {
                let cond_l = self.fresh_block("while.cond");
                let body_l = self.fresh_block("while.body");
                let end_l = self.fresh_block("while.end");

                self.line(format!("br label %{cond_l}"));
                self.start_block(&cond_l);
                let c = self.emit_expr(cond);
                self.line(format!("br i1 {c}, label %{body_l}, label %{end_l}"));

                self.start_block(&body_l);
                self.loops.push((cond_l.clone(), end_l.clone()));
                self.emit_block(body);
                self.loops.pop();
                if !self.terminated {
                    self.line(format!("br label %{cond_l}"));
                }

                self.start_block(&end_l);
            }
            Stmt::If { branches, orelse } => {
                let end_l = self.fresh_block("if.end");
                let mut else_l = String::new();

                for (i, (cond, body)) in branches.iter().enumerate() {
                    let then_l = self.fresh_block("if.then");
                    let last = i + 1 == branches.len();
                    let next_l = if last && orelse.is_empty() {
                        end_l.clone()
                    } else {
                        self.fresh_block("if.else")
                    };

                    let c = self.emit_expr(cond);
                    self.line(format!("br i1 {c}, label %{then_l}, label %{next_l}"));

                    self.start_block(&then_l);
                    self.emit_block(body);
                    if !self.terminated {
                        self.line(format!("br label %{end_l}"));
                    }

                    self.start_block(&next_l);
                    else_l = next_l;
                }

                if !orelse.is_empty() {
                    // current block is the final else
                    debug_assert_eq!(self.cur_block, else_l);
                    self.emit_block(orelse);
                    if !self.terminated {
                        self.line(format!("br label %{end_l}"));
                    }
                    self.start_block(&end_l);
                }
                // when orelse is empty the last `next_l` *is* end_l and is
                // already started
            }
        }
    }

    // ---- expressions ----

    /// Emit code for `expr`; returns the LLVM value (a temp or a constant).
    fn emit_expr(&mut self, expr: &Expr) -> String {
        match &expr.kind {
            ExprKind::ConstInt(v) => v.to_string(),
            ExprKind::ConstFloat(v) => fconst(*v),
            ExprKind::ConstBool(v) => v.to_string(),
            ExprKind::ConstStr(s) => self.intern_string(s),
            ExprKind::Local(name) => {
                let t = self.tmp();
                self.line(format!("{t} = load {}, ptr %v.{name}", lty(expr.ty)));
                t
            }
            ExprKind::Call { func, args } => {
                let mut arg_list = Vec::new();
                for arg in args {
                    let v = self.emit_expr(arg);
                    arg_list.push(format!("{} {v}", lty(arg.ty)));
                }
                let args_str = arg_list.join(", ");
                let callee = mangle(func);
                if expr.ty == Ty::None {
                    self.line(format!("call void @{callee}({args_str})"));
                    String::new()
                } else {
                    let t = self.tmp();
                    self.line(format!(
                        "{t} = call {} @{callee}({args_str})",
                        lty(expr.ty)
                    ));
                    t
                }
            }
            ExprKind::IntToFloat(inner) => {
                let v = self.emit_expr(inner);
                let t = self.tmp();
                self.line(format!("{t} = sitofp i64 {v} to double"));
                t
            }
            ExprKind::FloatToInt(inner) => {
                let v = self.emit_expr(inner);
                let t = self.tmp();
                // saturating: defined for NaN and out-of-range values
                self.line(format!("{t} = call i64 @llvm.fptosi.sat.i64.f64(double {v})"));
                t
            }
            ExprKind::BoolToInt(inner) => {
                let v = self.emit_expr(inner);
                let t = self.tmp();
                self.line(format!("{t} = zext i1 {v} to i64"));
                t
            }
            ExprKind::ToBool(inner) => {
                let v = self.emit_expr(inner);
                let t = self.tmp();
                match inner.ty {
                    Ty::Int => self.line(format!("{t} = icmp ne i64 {v}, 0")),
                    // une: NaN is truthy, like Python
                    Ty::Float => {
                        self.line(format!("{t} = fcmp une double {v}, {}", fconst(0.0)))
                    }
                    _ => unreachable!("ToBool only applies to numerics"),
                }
                t
            }
            ExprKind::Unary { op, operand } => {
                let v = self.emit_expr(operand);
                let t = self.tmp();
                match (op, operand.ty) {
                    (UnOp::Neg, Ty::Int) => self.line(format!("{t} = sub i64 0, {v}")),
                    (UnOp::Neg, Ty::Float) => self.line(format!("{t} = fneg double {v}")),
                    (UnOp::Not, Ty::Bool) => self.line(format!("{t} = xor i1 {v}, true")),
                    other => unreachable!("bad unary op {other:?}"),
                }
                t
            }
            ExprKind::Binary { op, left, right } => self.emit_binary(*op, left, right),
        }
    }

    fn emit_binary(&mut self, op: BinOp, left: &Expr, right: &Expr) -> String {
        // short-circuit and/or need control flow, not plain instructions
        if matches!(op, BinOp::And | BinOp::Or) {
            return self.emit_short_circuit(op, left, right);
        }

        let l = self.emit_expr(left);
        let r = self.emit_expr(right);
        let ty = left.ty; // semantic guarantees both sides match

        match op {
            BinOp::Add | BinOp::Sub | BinOp::Mul => {
                let instr = match (op, ty) {
                    (BinOp::Add, Ty::Int) => "add",
                    (BinOp::Sub, Ty::Int) => "sub",
                    (BinOp::Mul, Ty::Int) => "mul",
                    (BinOp::Add, Ty::Float) => "fadd",
                    (BinOp::Sub, Ty::Float) => "fsub",
                    (BinOp::Mul, Ty::Float) => "fmul",
                    other => unreachable!("bad arith {other:?}"),
                };
                let t = self.tmp();
                self.line(format!("{t} = {instr} {} {l}, {r}", lty(ty)));
                t
            }
            // true division: always float (semantic inserted the casts)
            BinOp::Div => {
                self.guard_zero(&r, Ty::Float, "ZeroDivisionError: division by zero");
                let t = self.tmp();
                self.line(format!("{t} = fdiv double {l}, {r}"));
                t
            }
            BinOp::FloorDiv => match ty {
                Ty::Int => {
                    self.guard_zero(
                        &r,
                        Ty::Int,
                        "ZeroDivisionError: integer division or modulo by zero",
                    );
                    let safe_r = self.guard_int_min(&l, &r);
                    let (q, r0) = self.emit_divmod(&l, &safe_r);
                    let adj = self.emit_floor_adjust(&r0, &safe_r);
                    let adj64 = self.tmp();
                    self.line(format!("{adj64} = zext i1 {adj} to i64"));
                    let t = self.tmp();
                    self.line(format!("{t} = sub i64 {q}, {adj64}"));
                    t
                }
                Ty::Float => {
                    self.guard_zero(&r, Ty::Float, "ZeroDivisionError: float floor division by zero");
                    let d = self.tmp();
                    self.line(format!("{d} = fdiv double {l}, {r}"));
                    let t = self.tmp();
                    self.line(format!("{t} = call double @llvm.floor.f64(double {d})"));
                    t
                }
                other => unreachable!("floordiv on {other:?}"),
            },
            BinOp::Mod => match ty {
                Ty::Int => {
                    self.guard_zero(
                        &r,
                        Ty::Int,
                        "ZeroDivisionError: integer division or modulo by zero",
                    );
                    let safe_r = self.guard_int_min(&l, &r);
                    let r0 = self.tmp();
                    self.line(format!("{r0} = srem i64 {l}, {safe_r}"));
                    let adj = self.emit_floor_adjust(&r0, &safe_r);
                    let sel = self.tmp();
                    self.line(format!("{sel} = select i1 {adj}, i64 {safe_r}, i64 0"));
                    let t = self.tmp();
                    self.line(format!("{t} = add i64 {r0}, {sel}"));
                    t
                }
                Ty::Float => {
                    self.guard_zero(&r, Ty::Float, "ZeroDivisionError: float modulo");
                    let r0 = self.tmp();
                    self.line(format!("{r0} = frem double {l}, {r}"));
                    // Python: nonzero remainder takes the divisor's sign
                    let rnz = self.tmp();
                    self.line(format!("{rnz} = fcmp one double {r0}, {}", fconst(0.0)));
                    let rneg = self.tmp();
                    self.line(format!("{rneg} = fcmp olt double {r0}, {}", fconst(0.0)));
                    let bneg = self.tmp();
                    self.line(format!("{bneg} = fcmp olt double {r}, {}", fconst(0.0)));
                    let sgn = self.tmp();
                    self.line(format!("{sgn} = xor i1 {rneg}, {bneg}"));
                    let adj = self.tmp();
                    self.line(format!("{adj} = and i1 {rnz}, {sgn}"));
                    let sel = self.tmp();
                    self.line(format!(
                        "{sel} = select i1 {adj}, double {r}, double {}",
                        fconst(0.0)
                    ));
                    let t = self.tmp();
                    self.line(format!("{t} = fadd double {r0}, {sel}"));
                    t
                }
                other => unreachable!("mod on {other:?}"),
            },
            BinOp::Eq | BinOp::Ne | BinOp::Lt | BinOp::Le | BinOp::Gt | BinOp::Ge => {
                let t = self.tmp();
                match ty {
                    Ty::Int => {
                        let cc = match op {
                            BinOp::Eq => "eq",
                            BinOp::Ne => "ne",
                            BinOp::Lt => "slt",
                            BinOp::Le => "sle",
                            BinOp::Gt => "sgt",
                            BinOp::Ge => "sge",
                            _ => unreachable!(),
                        };
                        self.line(format!("{t} = icmp {cc} i64 {l}, {r}"));
                    }
                    Ty::Float => {
                        // ordered except Ne: Python nan != x is True
                        let cc = match op {
                            BinOp::Eq => "oeq",
                            BinOp::Ne => "une",
                            BinOp::Lt => "olt",
                            BinOp::Le => "ole",
                            BinOp::Gt => "ogt",
                            BinOp::Ge => "oge",
                            _ => unreachable!(),
                        };
                        self.line(format!("{t} = fcmp {cc} double {l}, {r}"));
                    }
                    other => unreachable!("comparison on {other:?}"),
                }
                t
            }
            BinOp::And | BinOp::Or => unreachable!("handled above"),
        }
    }

    fn emit_short_circuit(&mut self, op: BinOp, left: &Expr, right: &Expr) -> String {
        let rhs_l = self.fresh_block("sc.rhs");
        let end_l = self.fresh_block("sc.end");

        let l = self.emit_expr(left);
        let lhs_block = self.cur_block.clone();
        let (skip_value, on_true, on_false) = match op {
            // a and b: if a is false, skip rhs and produce false
            BinOp::And => ("false", rhs_l.clone(), end_l.clone()),
            // a or b: if a is true, skip rhs and produce true
            BinOp::Or => ("true", end_l.clone(), rhs_l.clone()),
            _ => unreachable!(),
        };
        self.line(format!("br i1 {l}, label %{on_true}, label %{on_false}"));

        self.start_block(&rhs_l);
        let r = self.emit_expr(right);
        let rhs_block = self.cur_block.clone();
        self.line(format!("br label %{end_l}"));

        self.start_block(&end_l);
        let t = self.tmp();
        self.line(format!(
            "{t} = phi i1 [ {skip_value}, %{lhs_block} ], [ {r}, %{rhs_block} ]"
        ));
        t
    }

    /// Trap with a ZeroDivisionError when the divisor is zero.
    fn guard_zero(&mut self, divisor: &str, ty: Ty, message: &str) {
        let msg = self.intern_string(message);
        let is_zero = self.tmp();
        match ty {
            Ty::Int => self.line(format!("{is_zero} = icmp eq i64 {divisor}, 0")),
            Ty::Float => {
                self.line(format!("{is_zero} = fcmp oeq double {divisor}, {}", fconst(0.0)))
            }
            other => unreachable!("guard_zero on {other:?}"),
        }
        let trap_l = self.fresh_block("div.trap");
        let ok_l = self.fresh_block("div.ok");
        self.line(format!("br i1 {is_zero}, label %{trap_l}, label %{ok_l}"));
        self.start_block(&trap_l);
        self.line(format!("call void @pyrs_die(ptr {msg})"));
        self.line("unreachable");
        self.start_block(&ok_l);
    }

    /// `i64::MIN / -1` overflows (UB in sdiv/srem). Substitute divisor 1 in
    /// exactly that case: MIN/1 = MIN matches two's-complement wrapping and
    /// the remainder is 0, branch-free.
    fn guard_int_min(&mut self, dividend: &str, divisor: &str) -> String {
        let is_min = self.tmp();
        self.line(format!(
            "{is_min} = icmp eq i64 {dividend}, -9223372036854775808"
        ));
        let is_neg1 = self.tmp();
        self.line(format!("{is_neg1} = icmp eq i64 {divisor}, -1"));
        let overflow = self.tmp();
        self.line(format!("{overflow} = and i1 {is_min}, {is_neg1}"));
        let safe = self.tmp();
        self.line(format!("{safe} = select i1 {overflow}, i64 1, i64 {divisor}"));
        safe
    }

    fn emit_divmod(&mut self, l: &str, r: &str) -> (String, String) {
        let q = self.tmp();
        self.line(format!("{q} = sdiv i64 {l}, {r}"));
        let rem = self.tmp();
        self.line(format!("{rem} = srem i64 {l}, {r}"));
        (q, rem)
    }

    /// True when the truncated result must be adjusted for floored
    /// semantics: remainder nonzero and its sign differs from the divisor's.
    fn emit_floor_adjust(&mut self, rem: &str, divisor: &str) -> String {
        let rnz = self.tmp();
        self.line(format!("{rnz} = icmp ne i64 {rem}, 0"));
        let x = self.tmp();
        self.line(format!("{x} = xor i64 {rem}, {divisor}"));
        let sgn = self.tmp();
        self.line(format!("{sgn} = icmp slt i64 {x}, 0"));
        let adj = self.tmp();
        self.line(format!("{adj} = and i1 {rnz}, {sgn}"));
        adj
    }
}
