#!/usr/bin/env python3
"""Generate the runtime's Unicode tables from the CPython oracle.

The roadmap names the installed CPython as the specification for differential
tests, so the tables are derived by asking CPython itself about every code
point rather than by re-parsing the UCD. That gives agreement with the oracle
by construction, needs no network access in CI, and covers SpecialCasing
(U+00DF -> "SS"), which the `unicodedata` module does not expose.

Run it by hand and commit the output:

    python3 scripts/gen_unicode_tables.py

`make hygiene` checks that the stamped Unicode version still matches the
running interpreter, so a regeneration on a different CPython cannot land
unnoticed.
"""

import sys
import unicodedata
from pathlib import Path

MAX_CP = 0x110000
BLOCK = 128
OUT = Path(__file__).resolve().parent.parent / "codegen" / "runtime"

# Property bits, mirrored in unicode_data.h.
ALPHA = 1 << 0
DECIMAL = 1 << 1
DIGIT = 1 << 2
NUMERIC = 1 << 3
SPACE = 1 << 4
UPPER = 1 << 5
LOWER = 1 << 6
TITLECASED = 1 << 7  # single-char .istitle(): Lu or Lt
PRINTABLE = 1 << 8
XID_START = 1 << 9
XID_CONTINUE = 1 << 10
LINEBREAK = 1 << 11

# CPython's str.splitlines boundaries.
LINE_BREAKS = {
    0x0A, 0x0B, 0x0C, 0x0D, 0x1C, 0x1D, 0x1E, 0x85, 0x2028, 0x2029,
}


def props(cp, c):
    f = 0
    if c.isalpha():
        f |= ALPHA
    if c.isdecimal():
        f |= DECIMAL
    if c.isdigit():
        f |= DIGIT
    if c.isnumeric():
        f |= NUMERIC
    if c.isspace():
        f |= SPACE
    if c.isupper():
        f |= UPPER
    if c.islower():
        f |= LOWER
    if c.istitle():
        f |= TITLECASED
    if c.isprintable():
        f |= PRINTABLE
    if c.isidentifier():
        f |= XID_START
    if ("a" + c).isidentifier():
        f |= XID_CONTINUE
    if cp in LINE_BREAKS:
        f |= LINEBREAK
    return f


def main():
    # record: (flags, upper, lower, title, fold) where each mapping is a tuple
    # of code points. Deduplicated by making the mappings *relative* to the
    # code point when they are single-character, which is what lets whole
    # alphabets collapse onto one record.
    records = {}
    order = []
    index = [0] * MAX_CP

    for cp in range(MAX_CP):
        c = chr(cp)
        f = props(cp, c)
        up = tuple(ord(x) for x in c.upper())
        lo = tuple(ord(x) for x in c.lower())
        ti = tuple(ord(x) for x in c.title())
        fo = tuple(ord(x) for x in c.casefold())

        def rel(m):
            # single-character mappings become a delta so that, e.g., every
            # ASCII letter and every Cyrillic letter shares one record
            if len(m) == 1:
                return (1, m[0] - cp)
            return (len(m),) + m

        key = (f, rel(up), rel(lo), rel(ti), rel(fo))
        if key not in records:
            records[key] = len(order)
            order.append(key)
        index[cp] = records[key]

    if len(order) > 0xFFFF:
        sys.exit(f"too many distinct records for a uint16 index: {len(order)}")

    # Two-stage index: stage1[cp >> 7] selects a deduplicated block of 128.
    blocks = {}
    stage1 = []
    stage2 = []
    for base in range(0, MAX_CP, BLOCK):
        block = tuple(index[base:base + BLOCK])
        if block not in blocks:
            blocks[block] = len(stage2) // BLOCK
            stage2.extend(block)
        stage1.append(blocks[block])

    if len(stage2) // BLOCK > 0xFFFF:
        sys.exit("too many distinct blocks for a uint16 stage-1 entry")

    # Flatten the multi-character expansions into one shared array.
    ext = []
    ext_index = {}

    def put_ext(m):
        t = tuple(m)
        if t not in ext_index:
            ext_index[t] = len(ext)
            ext.extend(t)
        return ext_index[t]

    rows = []
    for f, up, lo, ti, fo in order:
        cells = []
        for m in (up, lo, ti, fo):
            n = m[0]
            if n == 1:
                cells.append((1, m[1]))  # count, delta
            else:
                cells.append((n, put_ext(m[1:])))  # count, offset into ext
        rows.append((f, cells))

    def carray(name, ctype, values, per_line=16):
        out = [f"const {ctype} {name}[{len(values)}] = {{"]
        for i in range(0, len(values), per_line):
            out.append("    " + ",".join(str(v) for v in values[i:i + per_line]) + ",")
        out.append("};")
        return "\n".join(out)

    version = unicodedata.unidata_version
    header = f"""/* GENERATED by scripts/gen_unicode_tables.py -- do not edit.
 *
 * Derived from CPython {sys.version.split()[0]}, Unicode {version}, which is
 * the oracle the differential tests compare against.
 */
#ifndef PYRS_UNICODE_DATA_H
#define PYRS_UNICODE_DATA_H

#include <stdint.h>

#define PYRS_UNIDATA_VERSION "{version}"
#define PYRS_UNIDATA_CPYTHON "{sys.version.split()[0]}"

#define PYRS_U_ALPHA        (1u << 0)
#define PYRS_U_DECIMAL      (1u << 1)
#define PYRS_U_DIGIT        (1u << 2)
#define PYRS_U_NUMERIC      (1u << 3)
#define PYRS_U_SPACE        (1u << 4)
#define PYRS_U_UPPER        (1u << 5)
#define PYRS_U_LOWER        (1u << 6)
#define PYRS_U_TITLECASED   (1u << 7)
#define PYRS_U_PRINTABLE    (1u << 8)
#define PYRS_U_XID_START    (1u << 9)
#define PYRS_U_XID_CONTINUE (1u << 10)
#define PYRS_U_LINEBREAK    (1u << 11)

/* Case mapping slots, in record order. */
#define PYRS_U_UPPER_MAP 0
#define PYRS_U_LOWER_MAP 1
#define PYRS_U_TITLE_MAP 2
#define PYRS_U_FOLD_MAP  3

/* One mapping: `count` code points. count == 1 means the result is
 * `cp + value`; otherwise `value` is an offset into pyrs_u_ext. */
typedef struct {{
    uint8_t count;
    int32_t value;
}} PyrsUMap;

typedef struct {{
    uint16_t flags;
    PyrsUMap maps[4];
}} PyrsURecord;

#define PYRS_U_BLOCK {BLOCK}

extern const uint16_t pyrs_u_stage1[{len(stage1)}];
extern const uint16_t pyrs_u_stage2[{len(stage2)}];
extern const PyrsURecord pyrs_u_records[{len(rows)}];
extern const uint32_t pyrs_u_ext[{len(ext)}];

/* The record for one code point. */
static inline const PyrsURecord *pyrs_u_lookup(uint32_t cp) {{
    if (cp >= 0x110000u) {{
        return &pyrs_u_records[0];
    }}
    uint32_t block = pyrs_u_stage1[cp / PYRS_U_BLOCK];
    return &pyrs_u_records[pyrs_u_stage2[block * PYRS_U_BLOCK + cp % PYRS_U_BLOCK]];
}}

static inline uint16_t pyrs_u_flags(uint32_t cp) {{
    return pyrs_u_lookup(cp)->flags;
}}

/* Write the mapping of `cp` in slot `slot` into `out` (>= 3 entries);
 * returns how many code points were written. */
static inline int pyrs_u_map(uint32_t cp, int slot, uint32_t *out) {{
    const PyrsUMap *m = &pyrs_u_lookup(cp)->maps[slot];
    if (m->count == 1) {{
        out[0] = (uint32_t)((int64_t)cp + m->value);
        return 1;
    }}
    for (int i = 0; i < m->count; i++) {{
        out[i] = pyrs_u_ext[(uint32_t)m->value + i];
    }}
    return m->count;
}}

#endif
"""

    body_rows = []
    for f, cells in rows:
        cs = ",".join(f"{{{n},{v}}}" for n, v in cells)
        body_rows.append(f"    {{{f},{{{cs}}}}},")
    body = f"""/* GENERATED by scripts/gen_unicode_tables.py -- do not edit.
 * CPython {sys.version.split()[0]}, Unicode {version}.
 */
#include "unicode_data.h"

{carray("pyrs_u_stage1", "uint16_t", stage1, 24)}

{carray("pyrs_u_stage2", "uint16_t", stage2, 24)}

{carray("pyrs_u_ext", "uint32_t", ext, 12)}

const PyrsURecord pyrs_u_records[{len(rows)}] = {{
{chr(10).join(body_rows)}
}};
"""

    (OUT / "unicode_data.h").write_text(header)
    (OUT / "unicode_data.c").write_text(body)
    print(f"CPython {sys.version.split()[0]}, Unicode {version}")
    print(f"  records {len(rows)}  stage1 {len(stage1)}  stage2 {len(stage2)}  ext {len(ext)}")
    print(f"  unicode_data.c {(OUT / 'unicode_data.c').stat().st_size / 1024:.1f} KiB")


if __name__ == "__main__":
    main()
