#!/usr/bin/env python3
"""Generate the tagged-int boundary case for the compatibility corpus.

`runtime.c` represents an int as `(v << 1) | 1` for v in +-2**62 and as a heap
pointer otherwise, and `codegen/src/intfast.rs` emits inline fast paths that
must agree with the runtime's bignum path at every boundary of that range.

The value list crosses each boundary and its immediate neighbours against
everything else, so small x small, small x heap, heap x small and heap x heap
all reach every guard. Run this and commit the output; it is not generated at
build time.
"""

import pathlib

SMALL_MAX = (1 << 62) - 1
SMALL_MIN = -(1 << 62)

VALUES = [
    0, 1, -1, 2, -2, 3, -3, 7, -7, 97, -97,
    2**31, -(2**31), 2**31 - 1, -(2**31) - 1, 2**32,
    2**61, -(2**61),
    SMALL_MAX, SMALL_MAX - 1, SMALL_MAX + 1,
    SMALL_MIN, SMALL_MIN + 1, SMALL_MIN - 1,
    2**63 - 1, -(2**63), 2**63,
    2**64, 10**30, -(10**30),
]

BODY = '''
n = len(vals)
for i in range(n):
    a = vals[i]
    print(a, -a, ~a, a == 0, a < 0)
    for j in range(n):
        b = vals[j]
        print(a + b, a - b, a * b)
        print(a < b, a <= b, a > b, a >= b, a == b, a != b)
        print(a & b, a | b, a ^ b)
        if b != 0:
            print(a // b, a % b)

# Division by zero keeps its exact type, message and catchability: the inline
# fast path routes a zero divisor to the runtime rather than trapping itself.
for i in range(n):
    a = vals[i]
    try:
        print(a // 0)
    except ZeroDivisionError as e:
        print("floordiv", e)
    try:
        print(a % 0)
    except ArithmeticError as e:
        print("mod", e)
'''


def main() -> None:
    lines = [
        "# Generated by scripts/gen_int_boundary.py -- do not edit by hand.",
        "#",
        "# Crosses every boundary of the tagged small-int representation",
        "# (+-2**62) against every operator that codegen inlines.",
        "",
        "vals: list[int] = [",
    ]
    lines += [f"    {v}," for v in VALUES]
    lines.append("]")
    out = pathlib.Path(__file__).resolve().parent.parent / "compatibility/cases/int_boundary.py"
    out.write_text("\n".join(lines) + BODY)
    print(f"{out}: {len(VALUES)} values, {len(VALUES) ** 2} pairs")


if __name__ == "__main__":
    main()
