/* GENERATED by scripts/gen_unicode_tables.py -- do not edit.
 *
 * Derived from CPython 3.14.7, Unicode 16.0.0, which is
 * the oracle the differential tests compare against.
 */
#ifndef PYRS_UNICODE_DATA_H
#define PYRS_UNICODE_DATA_H

#include <stdint.h>

#define PYRS_UNIDATA_VERSION "16.0.0"
#define PYRS_UNIDATA_CPYTHON "3.14.7"

#define PYRS_U_ALPHA        (1u << 0)
#define PYRS_U_DECIMAL      (1u << 1)
#define PYRS_U_DIGIT        (1u << 2)
#define PYRS_U_NUMERIC      (1u << 3)
#define PYRS_U_SPACE        (1u << 4)
#define PYRS_U_UPPER        (1u << 5)
#define PYRS_U_LOWER        (1u << 6)
#define PYRS_U_TITLECASED   (1u << 7)
#define PYRS_U_PRINTABLE    (1u << 8)
#define PYRS_U_XID_START    (1u << 9)
#define PYRS_U_XID_CONTINUE (1u << 10)
#define PYRS_U_LINEBREAK    (1u << 11)
#define PYRS_U_CASED        (1u << 12)
#define PYRS_U_CASE_IGNORABLE (1u << 13)

/* Case mapping slots, in record order. */
#define PYRS_U_UPPER_MAP 0
#define PYRS_U_LOWER_MAP 1
#define PYRS_U_TITLE_MAP 2
#define PYRS_U_FOLD_MAP  3

/* One mapping: `count` code points. count == 1 means the result is
 * `cp + value`; otherwise `value` is an offset into pyrs_u_ext. */
typedef struct {
    uint8_t count;
    int32_t value;
} PyrsUMap;

typedef struct {
    uint16_t flags;
    PyrsUMap maps[4];
} PyrsURecord;

#define PYRS_U_BLOCK 128

extern const uint16_t pyrs_u_stage1[8704];
extern const uint16_t pyrs_u_stage2[38144];
extern const PyrsURecord pyrs_u_records[311];
extern const uint32_t pyrs_u_ext[367];

/* The record for one code point. */
static inline const PyrsURecord *pyrs_u_lookup(uint32_t cp) {
    if (cp >= 0x110000u) {
        return &pyrs_u_records[0];
    }
    uint32_t block = pyrs_u_stage1[cp / PYRS_U_BLOCK];
    return &pyrs_u_records[pyrs_u_stage2[block * PYRS_U_BLOCK + cp % PYRS_U_BLOCK]];
}

static inline uint16_t pyrs_u_flags(uint32_t cp) {
    return pyrs_u_lookup(cp)->flags;
}

/* Write the mapping of `cp` in slot `slot` into `out` (>= 3 entries);
 * returns how many code points were written. */
static inline int pyrs_u_map(uint32_t cp, int slot, uint32_t *out) {
    const PyrsUMap *m = &pyrs_u_lookup(cp)->maps[slot];
    if (m->count == 1) {
        out[0] = (uint32_t)((int64_t)cp + m->value);
        return 1;
    }
    for (int i = 0; i < m->count; i++) {
        out[i] = pyrs_u_ext[(uint32_t)m->value + i];
    }
    return m->count;
}

#endif
