//! Multi-file module loading: resolve `import` / `from ... import`
//! transitively (including packages and relative imports), detect cycles,
//! and produce modules in topological order (dependencies first, root last)
//! for the semantic analyzer.
//!
//! Resolution order (first hit wins):
//! 1. the **root script's directory** (user code; wins on name clashes)
//! 2. **`PYRS_STDLIB`** if set and is a directory (dev/test shadowing)
//! 3. workspace **`stdlib/`** next to the `cli` crate when present (dev only)
//! 4. **embedded** stdlib baked into the `pyrs` binary (always available)
//!
//! A directory with `__init__.py` is a package; relative imports are rewritten
//! to absolute form before semantic analysis.
//!
//! **Partial package init:** a package `__init__.py` may import its own
//! submodules (`from . import mod`). While the package is being visited,
//! those children load without treating the parent edge as a cycle (like
//! CPython’s partially-initialized package). True mutual imports between
//! unrelated modules remain compile errors.

use std::collections::{HashMap, HashSet};
use std::path::{Path, PathBuf};

use common::Diagnostic;
use parser::ast;

/// Generated by `cli/build.rs` from workspace `stdlib/**/*.py`.
mod stdlib_embed {
    include!(concat!(env!("OUT_DIR"), "/stdlib_embed_data.rs"));
}

/// The entry/root module's synthetic name.
pub const ROOT_NAME: &str = "__main__";

/// A parsed module ready for analysis.
pub struct Loaded {
    /// Fully-qualified import name (`utils`, `pkg.mod`), or [`ROOT_NAME`].
    pub name: String,
    /// Path shown in diagnostics.
    pub display: String,
    pub source: String,
    /// AST with relative imports already rewritten to absolute (`level = 0`).
    pub ast: ast::Module,
}

/// A load failure already rendered against the right file.
#[derive(Debug)]
pub struct LoadError(pub String);

/// Where a module's source was found.
#[derive(Debug, Clone)]
enum ModuleLoc {
    /// Real filesystem path.
    File(PathBuf),
    /// Embedded stdlib (`display` is synthetic, e.g. `<stdlib>/os/path.py`).
    Embed {
        display: String,
        source: &'static str,
    },
}

/// Load the whole program starting from `root`. Returns modules in
/// topological order with the root last; the index is the diagnostic
/// file id.
pub fn load_program(root: &Path) -> Result<Vec<Loaded>, LoadError> {
    let entry = root
        .parent()
        .map(Path::to_path_buf)
        .unwrap_or_else(|| PathBuf::from("."));
    // Embedded stdlib is always consulted after filesystem roots.
    load_program_with_roots(root, &import_fs_roots(entry))
}

/// Filesystem import roots for [`load_program`], in search order:
/// entry dir, then `PYRS_STDLIB` (if set), then workspace `stdlib/` (if
/// present). Duplicates are skipped. Embed is **not** included — it is a
/// fallback inside [`resolve_module`].
fn import_fs_roots(entry: PathBuf) -> Vec<PathBuf> {
    import_fs_roots_from(entry, env_stdlib_root(), workspace_stdlib_root())
}

/// Pure assembly of filesystem roots (testable without env).
fn import_fs_roots_from(
    entry: PathBuf,
    env_stdlib: Option<PathBuf>,
    workspace: Option<PathBuf>,
) -> Vec<PathBuf> {
    let mut roots = vec![entry];
    if let Some(p) = env_stdlib {
        push_unique_root(&mut roots, p);
    }
    if let Some(p) = workspace {
        push_unique_root(&mut roots, p);
    }
    roots
}

fn push_unique_root(roots: &mut Vec<PathBuf>, p: PathBuf) {
    if !roots.iter().any(|r| r == &p) {
        roots.push(p);
    }
}

/// Like [`load_program`], but uses an explicit import search path for
/// **filesystem** roots. `roots[0]` should be the entry script directory.
/// First filesystem root that resolves a name wins; if none match, the
/// embedded stdlib is tried.
pub fn load_program_with_roots(root: &Path, roots: &[PathBuf]) -> Result<Vec<Loaded>, LoadError> {
    let mut state = LoadState {
        roots: roots.to_vec(),
        modules: HashMap::new(),
        order: Vec::new(),
        visiting: HashSet::new(),
    };

    let root_parsed = parse_file(root, ROOT_NAME, None, &state.roots)?;
    state.modules.insert(ROOT_NAME.to_string(), root_parsed);
    state.require(ROOT_NAME, common::Span::default(), ROOT_NAME)?;

    let mut out = Vec::new();
    for name in state.order {
        let p = state.modules.remove(&name).ok_or_else(|| {
            LoadError(format!(
                "internal error: module '{name}' missing from load graph after topo order \
                 (loader invariant broken)"
            ))
        })?;
        out.push(Loaded {
            name,
            display: p.display,
            source: p.source,
            ast: p.ast,
        });
    }
    Ok(out)
}

/// `PYRS_STDLIB` when set and is a directory.
fn env_stdlib_root() -> Option<PathBuf> {
    let p = PathBuf::from(std::env::var("PYRS_STDLIB").ok()?);
    if p.is_dir() { Some(p) } else { None }
}

/// Workspace `stdlib/` next to the `cli` crate (build-time path; optional).
fn workspace_stdlib_root() -> Option<PathBuf> {
    let default = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("stdlib");
    if default.is_dir() {
        Some(default)
    } else {
        None
    }
}

struct Parsed {
    display: String,
    source: String,
    ast: ast::Module,
    is_package: bool,
    /// Absolute module names this file depends on (leaves; parents are
    /// required automatically), each with the importing span.
    deps: Vec<(String, common::Span)>,
}

struct LoadState {
    /// Filesystem import roots only (embed is implicit after these).
    roots: Vec<PathBuf>,
    modules: HashMap<String, Parsed>,
    order: Vec<String>,
    visiting: HashSet<String>,
}

impl LoadState {
    /// Ensure `name` and its import graph are loaded and appear in `order`.
    fn require(&mut self, name: &str, span: common::Span, importer: &str) -> Result<(), LoadError> {
        if self.order.iter().any(|n| n == name) {
            return Ok(());
        }
        if self.visiting.contains(name) {
            // Package mid-init importing a child (or child touching parent):
            // allow if `name` is a proper package prefix of `importer`.
            if is_strict_package_prefix(name, importer) {
                return Ok(());
            }
            let (display, source) = self.importer_context(importer);
            let d = Diagnostic::new(
                common::Phase::Load,
                format!("circular import: '{importer}' and '{name}' import each other"),
                span,
            );
            return Err(LoadError(render(&d, &display, &source)));
        }

        self.ensure_loaded(name, span, importer)?;

        // Parents before children, unless the parent is already mid-init
        // (package `__init__` importing a submodule).
        if let Some(parent) = parent_name(name)
            && !self.visiting.contains(&parent)
        {
            self.require(&parent, span, importer)?;
        }

        self.visiting.insert(name.to_string());
        let deps = self.modules[name].deps.clone();
        for (dep, dep_span) in deps {
            self.require(&dep, dep_span, name)?;
        }
        self.visiting.remove(name);

        if !self.order.iter().any(|n| n == name) {
            self.order.push(name.to_string());
        }
        Ok(())
    }

    fn importer_context(&self, importer: &str) -> (String, String) {
        let p = &self.modules[importer];
        (p.display.clone(), p.source.clone())
    }

    /// Parse `name` and any missing parent packages into `modules`.
    fn ensure_loaded(
        &mut self,
        name: &str,
        span: common::Span,
        importer: &str,
    ) -> Result<(), LoadError> {
        if name == ROOT_NAME {
            return Ok(());
        }

        let parts: Vec<&str> = name.split('.').collect();
        for i in 1..=parts.len() {
            let partial = parts[..i].join(".");
            if let Some(existing) = self.modules.get(&partial) {
                if i < parts.len() && !existing.is_package {
                    let (display, source) = self.importer_context(importer);
                    let d = Diagnostic::new(
                        common::Phase::Load,
                        format!("No module named '{name}'; '{partial}' is not a package"),
                        span,
                    );
                    return Err(LoadError(render(&d, &display, &source)));
                }
                continue;
            }

            match resolve_module(&self.roots, &partial) {
                Some((loc, is_package)) => {
                    if i < parts.len() && !is_package {
                        let (display, source) = self.importer_context(importer);
                        let d = Diagnostic::new(
                            common::Phase::Load,
                            format!("No module named '{name}'; '{partial}' is not a package"),
                            span,
                        );
                        return Err(LoadError(render(&d, &display, &source)));
                    }
                    let package = package_of(&partial, is_package);
                    let parsed = parse_loc(loc, &partial, package, &self.roots)?;
                    self.modules.insert(partial, parsed);
                }
                None => {
                    let (display, source) = self.importer_context(importer);
                    let d = Diagnostic::new(
                        common::Phase::Load,
                        format!("No module named '{name}'"),
                        span,
                    );
                    return Err(LoadError(render(&d, &display, &source)));
                }
            }
        }
        Ok(())
    }
}

/// True if `parent` is a dotted prefix of `child` (`pkg` of `pkg.mod`).
fn is_strict_package_prefix(parent: &str, child: &str) -> bool {
    child.len() > parent.len()
        && child.as_bytes().get(parent.len()) == Some(&b'.')
        && child.starts_with(parent)
}

fn parent_name(name: &str) -> Option<String> {
    name.rsplit_once('.').map(|(p, _)| p.to_string())
}

/// `__package__` for a loaded module.
fn package_of(name: &str, is_package: bool) -> Option<String> {
    if is_package {
        Some(name.to_string())
    } else {
        parent_name(name)
    }
}

/// Locate `name` under filesystem roots first, then embedded stdlib.
///
/// **No split packages:** the top-level component is searched across roots
/// (then embed). Once a package is found under a given origin, children are
/// resolved only under that same origin (filesystem package directory or
/// embed), matching CPython’s package `__path__` spirit.
fn resolve_module(roots: &[PathBuf], name: &str) -> Option<(ModuleLoc, bool)> {
    let parts: Vec<&str> = name.split('.').filter(|p| !p.is_empty()).collect();
    if parts.is_empty() {
        return None;
    }

    let (top_loc, top_is_pkg) = resolve_top_level(roots, parts[0])?;
    if parts.len() == 1 {
        return Some((top_loc, top_is_pkg));
    }
    if !top_is_pkg {
        return None;
    }

    match top_loc {
        ModuleLoc::File(init_path) => resolve_children_under_dir(&init_path, &parts[1..]),
        ModuleLoc::Embed { .. } => resolve_children_in_embed(&parts),
    }
}

/// Top-level name only: first filesystem root, then embed.
fn resolve_top_level(roots: &[PathBuf], name: &str) -> Option<(ModuleLoc, bool)> {
    for root in roots {
        if let Some((path, is_package)) = resolve_under(root, name) {
            return Some((ModuleLoc::File(path), is_package));
        }
    }
    resolve_embedded(name)
}

/// Resolve nested components under a filesystem package directory.
/// `init_path` is the parent package's `__init__.py`. Does not search other
/// roots or embed.
fn resolve_children_under_dir(init_path: &Path, child_parts: &[&str]) -> Option<(ModuleLoc, bool)> {
    let mut pkg_dir = init_path.parent()?.to_path_buf();
    let mut loc = ModuleLoc::File(init_path.to_path_buf());
    let mut is_pkg = true;
    for &part in child_parts {
        if !is_pkg {
            return None;
        }
        let child_init = pkg_dir.join(part).join("__init__.py");
        if child_init.is_file() {
            loc = ModuleLoc::File(child_init);
            is_pkg = true;
            pkg_dir = pkg_dir.join(part);
            continue;
        }
        let mut child_py = pkg_dir.join(part);
        child_py.set_extension("py");
        if child_py.is_file() {
            loc = ModuleLoc::File(child_py);
            is_pkg = false;
            continue;
        }
        return None;
    }
    Some((loc, is_pkg))
}

/// Resolve a dotted name entirely within the embed (parent packages must
/// exist as packages in the embed).
fn resolve_children_in_embed(parts: &[&str]) -> Option<(ModuleLoc, bool)> {
    let mut last: Option<(ModuleLoc, bool)> = None;
    for i in 1..=parts.len() {
        let partial = parts[..i].join(".");
        let (loc, is_pkg) = resolve_embedded(&partial)?;
        if i < parts.len() && !is_pkg {
            return None;
        }
        last = Some((loc, is_pkg));
    }
    last
}

/// Filesystem-only resolve with package confinement (no embed). Used by unit tests.
#[cfg(test)]
fn resolve_module_path(roots: &[PathBuf], name: &str) -> Option<(PathBuf, bool)> {
    let parts: Vec<&str> = name.split('.').filter(|p| !p.is_empty()).collect();
    if parts.is_empty() {
        return None;
    }
    let mut found: Option<(PathBuf, bool)> = None;
    for root in roots {
        if let Some(hit) = resolve_under(root, parts[0]) {
            found = Some(hit);
            break;
        }
    }
    let (top_path, top_is_pkg) = found?;
    if parts.len() == 1 {
        return Some((top_path, top_is_pkg));
    }
    if !top_is_pkg {
        return None;
    }
    let (loc, is_pkg) = resolve_children_under_dir(&top_path, &parts[1..])?;
    match loc {
        ModuleLoc::File(p) => Some((p, is_pkg)),
        ModuleLoc::Embed { .. } => None,
    }
}

fn resolve_under(root: &Path, name: &str) -> Option<(PathBuf, bool)> {
    let rel: PathBuf = name.split('.').collect();
    let pkg_init = root.join(&rel).join("__init__.py");
    if pkg_init.is_file() {
        return Some((pkg_init, true));
    }
    let mut py = root.join(&rel);
    py.set_extension("py");
    if py.is_file() {
        return Some((py, false));
    }
    None
}

/// Resolve against sources embedded in the binary.
fn resolve_embedded(name: &str) -> Option<(ModuleLoc, bool)> {
    let rel: String = name.split('.').collect::<Vec<_>>().join("/");
    let pkg = format!("{rel}/__init__.py");
    if let Some(source) = stdlib_embed::embedded_source(&pkg) {
        return Some((
            ModuleLoc::Embed {
                display: format!("<stdlib>/{pkg}"),
                source,
            },
            true,
        ));
    }
    let mod_path = format!("{rel}.py");
    if let Some(source) = stdlib_embed::embedded_source(&mod_path) {
        return Some((
            ModuleLoc::Embed {
                display: format!("<stdlib>/{mod_path}"),
                source,
            },
            false,
        ));
    }
    None
}

fn module_exists(roots: &[PathBuf], name: &str) -> bool {
    resolve_module(roots, name).is_some()
}

fn parse_loc(
    loc: ModuleLoc,
    name: &str,
    package: Option<String>,
    roots: &[PathBuf],
) -> Result<Parsed, LoadError> {
    match loc {
        ModuleLoc::File(path) => parse_file(&path, name, package, roots),
        ModuleLoc::Embed { display, source } => {
            let is_package = display.ends_with("/__init__.py") || display.ends_with("__init__.py");
            parse_source(
                display,
                source.to_string(),
                name,
                package,
                is_package,
                roots,
            )
        }
    }
}

fn parse_file(
    path: &Path,
    name: &str,
    package: Option<String>,
    roots: &[PathBuf],
) -> Result<Parsed, LoadError> {
    let source = std::fs::read_to_string(path)
        .map_err(|e| LoadError(format!("failed to read {}: {e}", path.display())))?;
    let display = path.display().to_string();
    let is_package = path.file_name().is_some_and(|f| f == "__init__.py");
    parse_source(display, source, name, package, is_package, roots)
}

fn parse_source(
    display: String,
    source: String,
    name: &str,
    package: Option<String>,
    is_package: bool,
    roots: &[PathBuf],
) -> Result<Parsed, LoadError> {
    let mut module =
        parser::parse(&source).map_err(|d| LoadError(render(&d, &display, &source)))?;

    rewrite_relative_imports(&mut module, package.as_deref(), &display, &source)?;
    let deps = collect_deps(&module, name, roots);

    Ok(Parsed {
        display,
        source,
        ast: module,
        is_package,
        deps,
    })
}

/// Absolute module dependencies from a (relative-rewritten) AST.
/// Collects top-level **and** nested imports (function/if bodies), matching
/// CPython load behavior for deferred imports.
///
/// CPython `fromlist` uses `hasattr` on the source package: if a name is
/// already bound (assign/`def`/prior import), a same-named submodule is **not**
/// loaded. Self-imports use a bound-so-far walk at top level; nested imports
/// always load the named module (simple rule for this subset).
fn collect_deps(
    module: &ast::Module,
    self_name: &str,
    roots: &[PathBuf],
) -> Vec<(String, common::Span)> {
    let mut deps = Vec::new();
    let mut seen = HashSet::new();
    let mut bound: HashSet<String> = HashSet::new();
    let mut package_binds_cache: HashMap<String, HashSet<String>> = HashMap::new();
    collect_deps_in_stmts(
        &module.body,
        self_name,
        roots,
        &mut deps,
        &mut seen,
        &mut bound,
        &mut package_binds_cache,
        true,
    );
    deps
}

#[allow(clippy::too_many_arguments)]
fn collect_deps_in_stmts(
    stmts: &[ast::Stmt],
    self_name: &str,
    roots: &[PathBuf],
    deps: &mut Vec<(String, common::Span)>,
    seen: &mut HashSet<String>,
    bound: &mut HashSet<String>,
    package_binds_cache: &mut HashMap<String, HashSet<String>>,
    track_bound: bool,
) {
    for stmt in stmts {
        match &stmt.kind {
            ast::StmtKind::FuncDef(f) => {
                if track_bound {
                    bound.insert(f.name.clone());
                }
                collect_deps_in_stmts(
                    &f.body,
                    self_name,
                    roots,
                    deps,
                    seen,
                    bound,
                    package_binds_cache,
                    false,
                );
            }
            ast::StmtKind::Assign { targets, .. } if track_bound => {
                for t in targets {
                    collect_bound_names(t, bound);
                }
            }
            ast::StmtKind::AugAssign {
                target: ast::AssignTarget::Name { name, .. },
                ..
            } if track_bound => {
                bound.insert(name.clone());
            }
            ast::StmtKind::Import { names } => {
                for (m, alias, span) in names {
                    if m != "sys" && m != self_name && seen.insert(m.clone()) {
                        deps.push((m.clone(), *span));
                    }
                    if track_bound {
                        let local = alias
                            .clone()
                            .unwrap_or_else(|| m.split('.').next().unwrap_or(m).to_string());
                        bound.insert(local);
                    }
                }
            }
            ast::StmtKind::FromImport {
                module: m,
                names,
                span,
                ..
            } => {
                if m != "sys" && !m.is_empty() && m != self_name && seen.insert(m.clone()) {
                    deps.push((m.clone(), *span));
                }
                for (import_name, alias, nspan) in names {
                    let sub = if m.is_empty() {
                        import_name.clone()
                    } else {
                        format!("{m}.{import_name}")
                    };
                    if module_exists(roots, &sub) {
                        let from_self = m == self_name || m.is_empty();
                        let should_push = if from_self {
                            !track_bound || !bound.contains(import_name)
                        } else {
                            !package_binds_name_cached(roots, m, import_name, package_binds_cache)
                        };
                        if should_push && sub != self_name && seen.insert(sub.clone()) {
                            deps.push((sub, *nspan));
                        }
                    }
                    if track_bound {
                        let local = alias.clone().unwrap_or_else(|| import_name.clone());
                        bound.insert(local);
                    }
                }
            }
            ast::StmtKind::If { branches, orelse } => {
                for (_, b) in branches {
                    collect_deps_in_stmts(
                        b,
                        self_name,
                        roots,
                        deps,
                        seen,
                        bound,
                        package_binds_cache,
                        false,
                    );
                }
                collect_deps_in_stmts(
                    orelse,
                    self_name,
                    roots,
                    deps,
                    seen,
                    bound,
                    package_binds_cache,
                    false,
                );
            }
            ast::StmtKind::While { body, orelse, .. } | ast::StmtKind::For { body, orelse, .. } => {
                collect_deps_in_stmts(
                    body,
                    self_name,
                    roots,
                    deps,
                    seen,
                    bound,
                    package_binds_cache,
                    false,
                );
                collect_deps_in_stmts(
                    orelse,
                    self_name,
                    roots,
                    deps,
                    seen,
                    bound,
                    package_binds_cache,
                    false,
                );
            }
            ast::StmtKind::Try {
                body,
                handlers,
                orelse,
                finally,
            } => {
                collect_deps_in_stmts(
                    body,
                    self_name,
                    roots,
                    deps,
                    seen,
                    bound,
                    package_binds_cache,
                    false,
                );
                for h in handlers {
                    collect_deps_in_stmts(
                        &h.body,
                        self_name,
                        roots,
                        deps,
                        seen,
                        bound,
                        package_binds_cache,
                        false,
                    );
                }
                collect_deps_in_stmts(
                    orelse,
                    self_name,
                    roots,
                    deps,
                    seen,
                    bound,
                    package_binds_cache,
                    false,
                );
                collect_deps_in_stmts(
                    finally,
                    self_name,
                    roots,
                    deps,
                    seen,
                    bound,
                    package_binds_cache,
                    false,
                );
            }
            ast::StmtKind::With { body, .. } => {
                collect_deps_in_stmts(
                    body,
                    self_name,
                    roots,
                    deps,
                    seen,
                    bound,
                    package_binds_cache,
                    false,
                );
            }
            ast::StmtKind::Match { cases, .. } => {
                for c in cases {
                    collect_deps_in_stmts(
                        &c.body,
                        self_name,
                        roots,
                        deps,
                        seen,
                        bound,
                        package_binds_cache,
                        false,
                    );
                }
            }
            _ => {}
        }
    }
}

/// Whether `package` binds `name` at the end of its top-level body (any
/// assign/`def`/import). Used for external fromlist hasattr short-circuit.
/// Results are cached per package for a single [`collect_deps`] walk.
fn package_binds_name_cached(
    roots: &[PathBuf],
    package: &str,
    name: &str,
    cache: &mut HashMap<String, HashSet<String>>,
) -> bool {
    if let Some(bound) = cache.get(package) {
        return bound.contains(name);
    }
    let bound = package_bound_names(roots, package).unwrap_or_default();
    let hit = bound.contains(name);
    cache.insert(package.to_string(), bound);
    hit
}

/// Final top-level names bound by a package module body, if readable.
fn package_bound_names(roots: &[PathBuf], package: &str) -> Option<HashSet<String>> {
    let (loc, _) = resolve_module(roots, package)?;
    let source = match loc {
        ModuleLoc::File(path) => std::fs::read_to_string(path).ok()?,
        ModuleLoc::Embed { source, .. } => source.to_string(),
    };
    let ast = parser::parse(&source).ok()?;
    let mut bound = HashSet::new();
    for stmt in &ast.body {
        match &stmt.kind {
            ast::StmtKind::FuncDef(f) => {
                bound.insert(f.name.clone());
            }
            ast::StmtKind::Assign { targets, .. } => {
                for t in targets {
                    collect_bound_names(t, &mut bound);
                }
            }
            ast::StmtKind::AugAssign {
                target: ast::AssignTarget::Name { name: n, .. },
                ..
            } => {
                bound.insert(n.clone());
            }
            ast::StmtKind::Import { names } => {
                for (m, alias, _) in names {
                    let local = alias
                        .clone()
                        .unwrap_or_else(|| m.split('.').next().unwrap_or(m).to_string());
                    bound.insert(local);
                }
            }
            ast::StmtKind::FromImport { names, .. } => {
                for (import_name, alias, _) in names {
                    let local = alias.clone().unwrap_or_else(|| import_name.clone());
                    bound.insert(local);
                }
            }
            _ => {}
        }
    }
    Some(bound)
}

fn collect_bound_names(target: &ast::AssignTarget, names: &mut HashSet<String>) {
    match target {
        ast::AssignTarget::Name { name, .. } => {
            names.insert(name.clone());
        }
        ast::AssignTarget::Index { .. } => {}
        ast::AssignTarget::Tuple(items) => {
            for t in items {
                collect_bound_names(t, names);
            }
        }
        ast::AssignTarget::Starred { target, .. } => collect_bound_names(target, names),
    }
}

/// Turn relative `from` imports into absolute (`level = 0`) in place,
/// including imports nested in functions / control-flow blocks.
fn rewrite_relative_imports(
    module: &mut ast::Module,
    package: Option<&str>,
    display: &str,
    source: &str,
) -> Result<(), LoadError> {
    rewrite_relative_in_stmts(&mut module.body, package, display, source)
}

fn rewrite_relative_in_stmts(
    stmts: &mut [ast::Stmt],
    package: Option<&str>,
    display: &str,
    source: &str,
) -> Result<(), LoadError> {
    for stmt in stmts {
        match &mut stmt.kind {
            ast::StmtKind::FromImport {
                module: m,
                level,
                span,
                ..
            } => {
                if *level != 0 {
                    let abs = resolve_relative(*level, m, package).map_err(|msg| {
                        let d = Diagnostic::new(common::Phase::Load, msg, *span);
                        LoadError(render(&d, display, source))
                    })?;
                    *m = abs;
                    *level = 0;
                }
            }
            ast::StmtKind::FuncDef(f) => {
                rewrite_relative_in_stmts(&mut f.body, package, display, source)?;
            }
            ast::StmtKind::If { branches, orelse } => {
                for (_, b) in branches {
                    rewrite_relative_in_stmts(b, package, display, source)?;
                }
                rewrite_relative_in_stmts(orelse, package, display, source)?;
            }
            ast::StmtKind::While { body, orelse, .. } | ast::StmtKind::For { body, orelse, .. } => {
                rewrite_relative_in_stmts(body, package, display, source)?;
                rewrite_relative_in_stmts(orelse, package, display, source)?;
            }
            ast::StmtKind::Try {
                body,
                handlers,
                orelse,
                finally,
            } => {
                rewrite_relative_in_stmts(body, package, display, source)?;
                for h in handlers {
                    rewrite_relative_in_stmts(&mut h.body, package, display, source)?;
                }
                rewrite_relative_in_stmts(orelse, package, display, source)?;
                rewrite_relative_in_stmts(finally, package, display, source)?;
            }
            ast::StmtKind::With { body, .. } => {
                rewrite_relative_in_stmts(body, package, display, source)?;
            }
            ast::StmtKind::Match { cases, .. } => {
                for c in cases {
                    rewrite_relative_in_stmts(&mut c.body, package, display, source)?;
                }
            }
            _ => {}
        }
    }
    Ok(())
}

/// Resolve a relative import to an absolute module name (PEP 328).
fn resolve_relative(level: u32, module: &str, package: Option<&str>) -> Result<String, String> {
    let Some(pkg) = package else {
        return Err("attempted relative import with no known parent package".to_string());
    };
    let mut parts: Vec<&str> = pkg.split('.').filter(|p| !p.is_empty()).collect();
    if level as usize > parts.len() {
        return Err("attempted relative import beyond top-level package".to_string());
    }
    // level 1: current package; level 2: drop one component; …
    let keep = parts.len() - (level as usize - 1);
    parts.truncate(keep);
    if module.is_empty() {
        if parts.is_empty() {
            return Err("attempted relative import beyond top-level package".to_string());
        }
        Ok(parts.join("."))
    } else if parts.is_empty() {
        Ok(module.to_string())
    } else {
        Ok(format!("{}.{}", parts.join("."), module))
    }
}

/// Render a diagnostic against a specific file's source.
fn render(diag: &Diagnostic, display: &str, source: &str) -> String {
    if diag.span == common::Span::default() {
        format!("{diag}")
    } else {
        diag.render(display, source)
    }
}

#[cfg(test)]
mod tests {
    use super::{
        ModuleLoc, import_fs_roots_from, is_strict_package_prefix, load_program_with_roots,
        resolve_embedded, resolve_module, resolve_module_path, resolve_relative,
        rewrite_relative_imports, stdlib_embed,
    };
    use parser::ast;
    use std::path::PathBuf;

    #[test]
    fn relative_resolution() {
        assert_eq!(resolve_relative(1, "", Some("pkg")).unwrap(), "pkg");
        assert_eq!(resolve_relative(1, "mod", Some("pkg")).unwrap(), "pkg.mod");
        assert_eq!(resolve_relative(2, "", Some("pkg.sub")).unwrap(), "pkg");
        assert_eq!(resolve_relative(2, "a", Some("pkg.sub")).unwrap(), "pkg.a");
        assert_eq!(
            resolve_relative(2, "other", Some("pkg.sub")).unwrap(),
            "pkg.other"
        );
        assert!(resolve_relative(1, "x", None).is_err());
        assert!(resolve_relative(2, "", Some("pkg")).is_err());
        assert!(resolve_relative(3, "x", Some("pkg.sub")).is_err());
    }

    #[test]
    fn package_prefix() {
        assert!(is_strict_package_prefix("pkg", "pkg.mod"));
        assert!(is_strict_package_prefix("pkg.sub", "pkg.sub.m"));
        assert!(!is_strict_package_prefix("pkg", "pkg"));
        assert!(!is_strict_package_prefix("pkg", "pkgx"));
        assert!(!is_strict_package_prefix("a", "b"));
    }

    #[test]
    fn rewrite_relative_from_dot() {
        let mut m = parser::parse("from .mod import x\nfrom .. import y\n").unwrap();
        rewrite_relative_imports(&mut m, Some("pkg.sub"), "t.py", "from .mod import x\n").unwrap();
        assert!(matches!(
            &m.body[0].kind,
            ast::StmtKind::FromImport {
                module,
                level: 0,
                ..
            } if module == "pkg.sub.mod"
        ));
        assert!(matches!(
            &m.body[1].kind,
            ast::StmtKind::FromImport {
                module,
                level: 0,
                ..
            } if module == "pkg"
        ));
    }

    #[test]
    fn resolve_prefers_package_init() {
        let dir = std::env::temp_dir().join(format!("pyrs-modtest-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(dir.join("pkg")).unwrap();
        std::fs::write(dir.join("pkg/__init__.py"), "").unwrap();
        std::fs::write(dir.join("pkg/mod.py"), "").unwrap();
        let roots = [dir.clone()];
        let (p, is_pkg) = resolve_module_path(&roots, "pkg").unwrap();
        assert!(is_pkg);
        assert!(p.ends_with("__init__.py"));
        let (p2, is_pkg2) = resolve_module_path(&roots, "pkg.mod").unwrap();
        assert!(!is_pkg2);
        assert!(p2.ends_with("mod.py"));
        assert!(resolve_module_path(&roots, "nope").is_none());
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn resolve_searches_roots_in_order_user_wins() {
        let pid = std::process::id();
        let user = std::env::temp_dir().join(format!("pyrs-user-{pid}"));
        let stdlib = std::env::temp_dir().join(format!("pyrs-stdlib-{pid}"));
        let _ = std::fs::remove_dir_all(&user);
        let _ = std::fs::remove_dir_all(&stdlib);
        std::fs::create_dir_all(&user).unwrap();
        std::fs::create_dir_all(&stdlib).unwrap();

        std::fs::write(stdlib.join("only_std.py"), "x: int = 1\n").unwrap();
        std::fs::write(user.join("shared.py"), "x: int = 1\n").unwrap();
        std::fs::write(stdlib.join("shared.py"), "x: int = 2\n").unwrap();

        let roots = [user.clone(), stdlib.clone()];

        let (p, _) = resolve_module_path(&roots, "only_std").unwrap();
        assert!(p.starts_with(&stdlib));

        let (p, _) = resolve_module_path(&roots, "shared").unwrap();
        assert!(p.starts_with(&user));

        let _ = std::fs::remove_dir_all(&user);
        let _ = std::fs::remove_dir_all(&stdlib);
    }

    #[test]
    fn load_program_with_roots_finds_stdlib_module() {
        let pid = std::process::id();
        let user = std::env::temp_dir().join(format!("pyrs-load-user-{pid}"));
        let stdlib = std::env::temp_dir().join(format!("pyrs-load-std-{pid}"));
        let _ = std::fs::remove_dir_all(&user);
        let _ = std::fs::remove_dir_all(&stdlib);
        std::fs::create_dir_all(&user).unwrap();
        std::fs::create_dir_all(&stdlib).unwrap();

        std::fs::write(stdlib.join("libmod.py"), "VALUE: int = 42\n").unwrap();
        let main = user.join("main.py");
        std::fs::write(&main, "import libmod\nprint(libmod.VALUE)\n").unwrap();

        let roots = [user.clone(), stdlib.clone()];
        let loaded = load_program_with_roots(&main, &roots).unwrap();
        let names: Vec<_> = loaded.iter().map(|m| m.name.as_str()).collect();
        assert!(names.contains(&"libmod"));
        assert_eq!(names.last().copied(), Some("__main__"));

        let _ = std::fs::remove_dir_all(&user);
        let _ = std::fs::remove_dir_all(&stdlib);
    }

    #[test]
    fn embed_contains_os_path() {
        assert!(
            stdlib_embed::embedded_source("os/path.py").is_some(),
            "os/path.py should be embedded in the pyrs binary"
        );
        assert!(stdlib_embed::embedded_source("os/__init__.py").is_some());
        let paths = stdlib_embed::embedded_paths();
        assert!(paths.contains(&"os/path.py"));
    }

    #[test]
    fn resolve_embedded_os_path() {
        let (loc, is_pkg) = resolve_embedded("os").expect("embedded os package");
        assert!(is_pkg);
        match loc {
            ModuleLoc::Embed { display, source } => {
                assert_eq!(display, "<stdlib>/os/__init__.py");
                // Re-exports `path` for `import os` → `os.path`.
                assert!(source.contains("from . import path"), "source={source:?}");
            }
            ModuleLoc::File(_) => panic!("expected embed"),
        }
        let (loc, is_pkg) = resolve_embedded("os.path").expect("embedded os.path");
        assert!(!is_pkg);
        match loc {
            ModuleLoc::Embed { display, source } => {
                assert_eq!(display, "<stdlib>/os/path.py");
                assert!(source.contains("def join"), "source={source:?}");
                assert!(source.contains("def dirname"), "source={source:?}");
                assert!(source.contains("def basename"), "source={source:?}");
            }
            ModuleLoc::File(_) => panic!("expected embed"),
        }
        assert!(resolve_embedded("nope_missing").is_none());
    }

    #[test]
    fn import_fs_roots_stacks_env_then_workspace() {
        let entry = PathBuf::from("/entry");
        let env = PathBuf::from("/env-std");
        let ws = PathBuf::from("/ws-std");
        let roots = import_fs_roots_from(entry.clone(), Some(env.clone()), Some(ws.clone()));
        assert_eq!(roots, vec![entry.clone(), env.clone(), ws.clone()]);

        // Env alone, no workspace.
        let roots = import_fs_roots_from(entry.clone(), Some(env.clone()), None);
        assert_eq!(roots, vec![entry.clone(), env.clone()]);

        // Workspace alone (no PYRS_STDLIB).
        let roots = import_fs_roots_from(entry.clone(), None, Some(ws.clone()));
        assert_eq!(roots, vec![entry.clone(), ws.clone()]);

        // Duplicate path not pushed twice.
        let roots = import_fs_roots_from(entry.clone(), Some(ws.clone()), Some(ws.clone()));
        assert_eq!(roots, vec![entry, ws]);
    }

    #[test]
    fn incomplete_user_package_does_not_split_with_embed() {
        // User shadows package name with incomplete package; child must NOT
        // load from embed (no split-package across origins).
        let pid = std::process::id();
        let user = std::env::temp_dir().join(format!("pyrs-split-embed-{pid}"));
        let _ = std::fs::remove_dir_all(&user);
        std::fs::create_dir_all(user.join("os")).unwrap();
        std::fs::write(user.join("os/__init__.py"), "# incomplete\n").unwrap();
        // no os/path.py on user

        let roots = [user.clone()];
        assert!(matches!(
            resolve_module(&roots, "os"),
            Some((ModuleLoc::File(_), true))
        ));
        assert!(
            resolve_module(&roots, "os.path").is_none(),
            "must not pull os.path from embed when user owns package os"
        );

        let main = user.join("main.py");
        std::fs::write(&main, "import os.path\nprint(1)\n").unwrap();
        let err = match load_program_with_roots(&main, &roots) {
            Err(e) => e,
            Ok(_) => panic!("expected load error for incomplete package shadow"),
        };
        assert!(err.0.contains("No module named 'os.path'"), "err={}", err.0);

        let _ = std::fs::remove_dir_all(&user);
    }

    #[test]
    fn incomplete_user_package_does_not_split_with_second_root() {
        let pid = std::process::id();
        let user = std::env::temp_dir().join(format!("pyrs-split-user-{pid}"));
        let stdlib = std::env::temp_dir().join(format!("pyrs-split-std-{pid}"));
        let _ = std::fs::remove_dir_all(&user);
        let _ = std::fs::remove_dir_all(&stdlib);
        std::fs::create_dir_all(user.join("os")).unwrap();
        std::fs::create_dir_all(stdlib.join("os")).unwrap();
        std::fs::write(user.join("os/__init__.py"), "").unwrap();
        std::fs::write(stdlib.join("os/__init__.py"), "from . import path\n").unwrap();
        std::fs::write(
            stdlib.join("os/path.py"),
            "def join(a: str, b: str) -> str:\n    return a + b\n",
        )
        .unwrap();

        let roots = [user.clone(), stdlib.clone()];
        assert!(resolve_module_path(&roots, "os.path").is_none());
        assert!(resolve_module(&roots, "os.path").is_none());

        let main = user.join("main.py");
        std::fs::write(&main, "from os.path import join\n").unwrap();
        let err = match load_program_with_roots(&main, &roots) {
            Err(e) => e,
            Ok(_) => panic!("expected load error for incomplete package shadow"),
        };
        assert!(err.0.contains("No module named 'os.path'"), "err={}", err.0);

        let _ = std::fs::remove_dir_all(&user);
        let _ = std::fs::remove_dir_all(&stdlib);
    }

    #[test]
    fn load_from_embed_without_disk_stdlib() {
        // Only the user entry dir as a filesystem root — no disk stdlib.
        // `os.path` must still resolve via the embedded sources.
        let pid = std::process::id();
        let user = std::env::temp_dir().join(format!("pyrs-embed-user-{pid}"));
        let _ = std::fs::remove_dir_all(&user);
        std::fs::create_dir_all(&user).unwrap();

        let main = user.join("main.py");
        std::fs::write(
            &main,
            "from os.path import join\nprint(join(\"a\", \"b\"))\n",
        )
        .unwrap();

        let roots = [user.clone()]; // no stdlib on disk in roots
        // Still finds os via embed after filesystem miss.
        assert!(
            resolve_module(&roots, "os.path").is_some(),
            "os.path should resolve from embed when not on disk roots"
        );
        let loaded = load_program_with_roots(&main, &roots).unwrap();
        let names: Vec<_> = loaded.iter().map(|m| m.name.as_str()).collect();
        assert!(names.contains(&"os"), "names={names:?}");
        assert!(names.contains(&"os.path"), "names={names:?}");
        assert_eq!(names.last().copied(), Some("__main__"));
        // Display path is synthetic for embed.
        let path_mod = loaded.iter().find(|m| m.name == "os.path").unwrap();
        assert!(
            path_mod.display.starts_with("<stdlib>/"),
            "display={}",
            path_mod.display
        );

        let _ = std::fs::remove_dir_all(&user);
    }

    #[test]
    fn user_module_wins_over_embed() {
        let pid = std::process::id();
        let user = std::env::temp_dir().join(format!("pyrs-user-wins-embed-{pid}"));
        let _ = std::fs::remove_dir_all(&user);
        std::fs::create_dir_all(user.join("os")).unwrap();
        // Shadow the embedded `os` package with a trivial user package.
        std::fs::write(user.join("os/__init__.py"), "MARKER: int = 7\n").unwrap();
        let main = user.join("main.py");
        std::fs::write(&main, "import os\nprint(os.MARKER)\n").unwrap();

        let roots = [user.clone()];
        let (loc, is_pkg) = resolve_module(&roots, "os").unwrap();
        assert!(is_pkg);
        match loc {
            ModuleLoc::File(p) => assert!(p.starts_with(&user)),
            ModuleLoc::Embed { .. } => panic!("user package must win over embed"),
        }
        let loaded = load_program_with_roots(&main, &roots).unwrap();
        let os_mod = loaded.iter().find(|m| m.name == "os").unwrap();
        assert!(os_mod.source.contains("MARKER"));
        assert!(!os_mod.display.starts_with("<stdlib>/"));

        let _ = std::fs::remove_dir_all(&user);
    }
}
